### PR TITLE
[connectivity_plus_macos] backport to macOS 10.11

### PR DESCRIPTION
**Pull request by alexbatalov**
## Description

#417 has brought ethernet support to macOS at expense of leaving behind 3 major versions (10.11, 10.12, 10.13). Flutter team is working hard to keep OS requirements as low as possible and I think adding one more connectivity type does not fit very well into that goal. This PR restores compatibility with earlier OS versions via [Reachability.swift](https://github.com/ashleymills/Reachability.swift) (without ethernet support). On modern versions (10.14+) it keeps using `NWPathMonitor` introduced in #417.

In addition it fixes a small bug in `NWPathMonitor` usage. It was configured to deliver path update events on background queue, which is then passed to Flutter without jumping back to main queue.

## Related Issues

#417 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by diegotori** [comment]
LGTM.

**Comment by mhadaily** [comment]
can you please rebase with `main` 

please add changelog to the package and please pump version too thanks

**Review by mhadaily — APPROVED** [review]
LGTM

**Comment by mhadaily** [comment]
@alexbatalov can you please add a changelog to the main package as well as pump the version accordingly? then let's merge it.

**Pull request merged**
