### PR TITLE
fix(network_info_plus): import original `getgateway.*` from libnatpmp

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

- Remove [`getgateway.*`](https://github.com/fluttercommunity/plus_plugins/pull/355) copied from SO
- Add original, properly attributed [`getgateway.*`](https://github.com/miniupnp/libnatpmp/blob/master/getgateway.c) from libnatpmp
- Add libnatpmp to `network_info_plus/LICENSE`
- Adapt `FLTNetworkInfoPlusPlugin.m` & restore "en0" check

Disclaimer: I'm no iOS developer but I've tested this in a simulator:

## Related Issues

Fixes: #1058

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jpnurmi** [comment]
Screenshot 2023-03-04 at 11 13 29

**Review by nohli — APPROVED** [review]
Great!

**Review by vbuberen — APPROVED** [review]

**Comment by vbuberen** [comment]
Thank you very much for resolving this problem

**Comment by mhadaily** [comment]
Awesome JP

**Pull request merged**
