### PR TITLE
refactor(all): move e2e tests to example/test_driver and update docs

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

Moved all e2e tests to the example/test_driver folder.

## Related Issues

- https://github.com/fluttercommunity/plus_plugins/issues/28

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jpnurmi** [comment]
- Move `sensors_plus/test/sensors_e2e.dart` to `sensors_plus/example/test_driver/`, and
- remove `connectivity_plus/test/connectivity_e2e.dart` (looks like duplicate of the one in test_driver)?

P.S. Are these missing how does one run flutter drive for battery & share?
- `battery_plus/example/test_driver/battery_e2e_test.dart`
- `share_plus/example/test_driver/share_e2e.dart`

**Comment by miquelbeltran** [comment]
Thanks for checking those!

- sensors -> fixed
- connectivity -> removed duplicated
- share -> looks like the original `share_test.dart` was the e2e, so renamed and moved.
- battery -> looks like the `battery_e2e_test.dart` was originally missing

**Comment by miquelbeltran** [comment]
I added the missing `batter_e2e_test.dart` and I was able to run and pass the test with `flutter drive --target=./test_driver/battery_e2e.dart`

**Review by jpnurmi — APPROVED** [review]
Awesome!

**Pull request merged**
