### PR TITLE
[device_info_plus_ios] fix identifierForVendor

### LINKED ISSUE #621: [device_info_plus] crash
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]

```shell
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x129708 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x19b9c8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1a7a20 -[__NSPlaceholderDictionary initWithCapacity:].cold.1
4  CoreFoundation                 0x164c0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x8de0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  Runner                         0x332488 -[FLTDeviceInfoPlusPlugin handleMethodCall:result:] + 23 (FLTDeviceInfoPlusPlugin.m:23)
```

### PR DESCRIPTION
**Pull request by alexbatalov**
## Description

This PR likely fixes #621. Of all used `UIDevice` properties only `identifierForVendor` is marked as [nullable](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor?language=objc). However the circumstances when it is null are hard to reproduce, so it's a guess.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by miquelbeltran — APPROVED** [review]
LGTM! Like in the other PR, could you also add a new entry on the CHANGELOG and update the version number in the pubspec? thanks!

**Comment by miquelbeltran** [comment]
hey @alexbatalov some conflicts appeared, could you fix them? please ping me when ready and I will merge

**Comment by alexbatalov** [comment]
@miquelbeltran I've updated version and changelog, but there is other failing check, see #661, which fixes failing test in `package_info_plus`, which itself fails because there is a missing changelog in `network_info_plus` (see #655).

**Comment by miquelbeltran** [comment]
thanks @alexbatalov I will finish merging and releasing once I am back in the office

**Review by vbuberen — APPROVED** [review]

**Comment by mhadaily** [comment]
@alexbatalov can you please resolve the conflicts then I will merge and release a new package.

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
