### PR TITLE
Preview release versions

### PR DESCRIPTION
**Pull request by jpnurmi**
As mentioned in https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

> We’ve also added a new feature to pub.dev that tags package versions as preview releases when their dependent Dart SDK hasn’t yet been released to stable. Preview releases will automatically be promoted to regular stable versions once a new stable Dart SDK is released.

### CODE REVIEW

**Comment by jpnurmi** [comment]
All packages with `0.x.y-nullsafety.z` versions were bumped up to `1.0.0`, and those that had been already bumped up to `1.0.0-nullsafety.x` the suffix was simply dropped.

**Comment by jpnurmi** [comment]
Furthermore, `dart pub upgrade --null-safety` was run for all packages. Only some minor manual adjustments were needed mostly to avoid conflicts with `flutter_driver`.

**Comment by jpnurmi** [comment]
- The integration test fails because of https://github.com/flutter/flutter/issues/76446
- The analysis fails because of a pre-release vs. preview warning, which is fine at this stage:
    ```
    Package validation found the following potential issue:
    * Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
      See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases.
    
    Package has 1 warning.
    ```

**Review by miquelbeltran — APPROVED** [review]
Thanks a lot! nice to see all the packages with major versions now :)

**Comment by jpnurmi** [comment]
Thanks! All packages have been published - we're all set!

@mhadaily Could you merge this, please? I'm not able to do so because of the (harmless) `pub publish` preview/pre-release related warning that makes the CI analysis check fail.

**Comment by mhadaily** [comment]
@jpnurmi done

**Pull request merged**
