### PR TITLE
feat(sensors_plus): add magnetometer support

### PR DESCRIPTION
**Pull request by Zabadam**
## Description

- Adds necessary Android, iOS, and web API for magnetometer sensor.

- Adds new `MagnetometerEvent` class
  - Secondary commit suggests small typo fix in constructors of other `FooEvent` classes

- Adds new `Stream<MagnetometerEvent>` called `magnetometerEvents`.

## Related Issues

#370 [[sensors_plus]: Addition of Magnetometer](https://github.com/fluttercommunity/plus_plugins/issues/370)

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] Testing has been performed to verify Android support.
- [ ] Testing has been performed to verify iOS support.
- [ ] Testing has been performed to verify web support.
  - Any browser I tried testing triggered 

```
. . .
else if (error.toString().contains('ReferenceError')) {
  print('$apiName is not supported by the User Agent.');
}
```
> where `$apiName` is the newly added `Magnetometer()`.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by mhadaily** [comment]
Thanks for the PR, it looks good and is a nice feature to be added to the package.

**Comment by Zabadam** [comment]
Glad to hear that! 

I see there were some snags in the tests. Ths Swift formatting... I'm not sure. The portions I added were duplicated from the other identical bits. I do not have a formatter for Swift.

The "missing" tests, as far as I can tell, are in place.

Would love to get whatever is needed done to push this forward! 👍

**Comment by mhadaily** [comment]
Please let podspec be as is. 

btw, it seems you can get the formatting, did you run `melos run format`? do you have `clang-format` installed on your machine?

**Comment by Zabadam** [comment]
> Please let podspec be as is.

Done.

> btw, it seems you can get the formatting, did you run `melos run format`? do you have `clang-format` installed on your machine?

I have troubles with melos. I got it to `bootstrap` thankfully, but any other commands like `clean` or `run format` give me a 
"No active package melos" error. I thought it might be clang, so it assuring to hear you suggest that. I'll keep looking.

**Comment by Zabadam** [comment]
Just a friendly reminder that this PR is ready for review.

I would love to have this functionality added to `sensors_plus`!

**Comment by mhadaily** [comment]
Great, I'll review it this weekend and will release new version.

**Comment by Zabadam** [comment]
Interestingly enough after I ran `melos run format` and pushed, I saw a change waiting for a new push. Likely something with my auto-format when saving in VS Code.

I will try that again.

**Comment by Zabadam** [comment]
> Interesting, I saw you fixed that previously, maybe you should try once more.

Easy fix 🤞 ready to go.

**Comment by Zabadam** [comment]
codecov is showing a change in a file for `connectivity_plus` that I did not make intentionally but may be a result of some automatic formatting.

Actually I manually checked [the alleged change](https://codecov.io/gh/fluttercommunity/plus_plugins/compare/43d90772365d7a14a4a72cca2c5c97bbee6b3076...95107711786f502b7922cd7afdda930879628b2e/changes 'codecov coverage differences') in my repository and found the "missing" line still present. 🤔

**Comment by Zabadam** [comment]
What is my next step?

**Comment by mhadaily** [comment]
@Zabadam it's great, I am going to merge this actually, I thought I wrote to you but it seems I forgot, Can you just once more merge with `main` and make sure everything is up to date and also double-check the version number. we had a few releases for these packages. 
that's it, I will merge it right away afterward.

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
