### PR TITLE
fix(share_plus): export XFile

### LINKED ISSUE #1271: [Question]: the class XFILE doesn't exist.
### What is your question?

1. I create a class and wanted to use "Share.shareXFiles".
2. I add "import 'package:share_plus/share_plus.dart';"
3. When writting this line : await Share.shareXFiles([XFile(filename)],     I have this message : The method 'XFile' isn't defined for the type 'DataShareService'.
4. So I have to add this import "import 'package:cross_file/cross_file.dart';"
5. But now I have this message "package:cross_file/cross_file.dart Depend on referenced packages.dart[depend_on_referenced_packages](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html)"

In your example, you don't have the problem because XFile is referenced by this import : 'package:image_picker/image_picker.dart'

In the example below, I have commented the line of the import 'package:cross_file/cross_file.dart' so you can see the problem. If you uncomment the import 'package:cross_file/cross_file.dart'; you'll see the other message.
Thanks.

Code sample :

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
// TODO : uncomment the line below to refrence XFile
//import 'package:cross_file/cross_file.dart';

class DataShareService {
  void sharingFile({
    required String filename,
    required BuildContext context,
    required String subject,
  }) async {

    final box = context.findRenderObject() as RenderBox?;

    await Share.shareXFiles([XFile(filename)],
        subject: subject,
        sharePositionOrigin: box!.localToGlobal(Offset.zero) & box.size);
  }
}

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by werainkhatri**
## Description

- moved `SharePlatform` to `platform_interface/share_plus_platform`.
- exported `cross_file` and `share_plus_platform` in `share_plus_platform_interface.dart` file ([inspiration](https://github.com/flutter/plugins/blob/f55c7ffc6984c75e6b2b6a72a02b48064e0b5bc1/packages/image_picker/image_picker_platform_interface/lib/image_picker_platform_interface.dart#L5)).
- exported (by `export ... show ...;`) `XFile` in `share_plus` package ([inspiration](https://github.com/flutter/plugins/blob/f55c7ffc6984c75e6b2b6a72a02b48064e0b5bc1/packages/image_picker/image_picker/lib/image_picker.dart#L18)).
- hid `XFile` from `file_selector` and `image_picker` in `example/lib/main.dart` so that this export is tested.

wild ideas, not to be taken too seriously:
1. should the folders in `share_plus_platform_interface/lib` be moved to `src` (same as [`image_picker`](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker_platform_interface/lib))?
2. Should `SharePlatform` be renamed to `SharePlusPlatform`?

## Related Issues

Fixes #1271

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by miquelbeltran — APPROVED** [review]
LGTM

**Comment by SirusCodes** [comment]
@miquelbeltran when this will be published?

**Comment by miquelbeltran** [comment]
We don't have yet a fixed release schedule, but probably during the coming days

**Comment by SirusCodes** [comment]
Ok can you give an ETA as it is blocking #1070 since published version is not exporting XFile

Should I make a draft PR by depending using path?

**Comment by SirusCodes** [comment]
> if you do a proper development setup using melos. So you don't even need to add the dependency by path because your pubspec lock already references it.

I have never used melos. Will try to configure it. Thanks👍

**Comment by miquelbeltran** [comment]
> I have never used melos. Will try to configure it. Thanks+1

It is on the Contributors guide, you need it to bootstrap the repo.

Please read the contributors guide carefully and follow it.

**Pull request merged**
