### PR TITLE
[device_info_plus] Added more information for Windows

### LINKED ISSUE #177: [device_info_plus]<windows> add more information return like MacAddress , windowsVersion , ...
I want lock windows app for specific hardware for some reasons to do this I need get some unique keys from clients hardware like 'bios UUID' or 'MacAddress' but I didn't find any thing for flutter desktop windows platform. there are packages for Android and ios that returns MAC and bios UUID like platform_device_id and device_info but they don't support desktop platform, finally I found plus plugins that support device info for windows but there are few properties presented! I think this should be grow with necessary properties like bios UUID or something unique for hardware / MacAdress / windows Version / userName / and so forth!

### PR DESCRIPTION
**Pull request by alexmercerind**
## Description

Now `device_info_plus` fetches a lot more information on Windows compared to before.
This has many use-cases like identifying Windows version, getting username, install date, build number or product ID (for software license handling) etc.

### Reference Images
[sensitive data is hidden]

**Windows 10**

device_info_plus_10

**Windows 11**

device_info_plus_11

```dart
{
  'computerName': computerName,
  'numberOfCores': numberOfCores,
  'systemMemoryInMegabytes': systemMemoryInMegabytes,
  'userName': userName,
  'majorVersion': majorVersion,
  'minorVersion': minorVersion,
  'buildNumber': buildNumber,
  'platformId': platformId,
  'csdVersion': csdVersion,
  'servicePackMajor': servicePackMajor,
  'servicePackMinor': servicePackMinor,
  'suitMask': suitMask,
  'productType': productType,
  'reserved': reserved,
  'buildLab': buildLab,
  'buildLabEx': buildLabEx,
  'digitalProductId': digitalProductId,
  'displayVersion': displayVersion,
  'editionId': editionId,
  'installDate': installDate,
  'productId': productId,
  'productName': productName,
  'registeredOwner': registeredOwner,
  'releaseId': releaseId,
  'deviceId': deviceId,
}
```

## Related Issues

Closes #177

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by alexmercerind** [comment]
## Reference Images

**Windows 10**

device_info_plus_10

**Windows 11**

device_info_plus_11

**Comment by alexmercerind** [comment]
cc @mhadaily.

Thanks a lot!

**Comment by miquelbeltran** [comment]
Very cool, thanks! I will test this before approving and merging when I got time.

Meanwhile, is there any way you could add a test or two? so then codecov won't complain.

**Comment by alexmercerind** [comment]
Thanks for the follow up @miquelbeltran!

I improved the tests for Windows, but it seems we're currently using `ubuntu-latest` (even on Windows). And DLLs required for the native calls cannot be located on Linux.

https://github.com/fluttercommunity/plus_plugins/blob/08a7a35502d2498ea3dd1473445b4511dea35518/.github/workflows/device_info_plus.yaml#L68-L79

Any solution that seems good to you?
Thanks.

**Comment by miquelbeltran** [comment]
Hi @alexmercerind 

I saw that the test_and_coverage job is failing in the device_info_plus_windows project. Can you take a look? 

I haven't looked into it, but I guess you need to have a way to mock the calls to the missing dll in the tests

**Comment by Fraa-124** [comment]
Please merge this! this is a must for managing devices!!

**Comment by jaxnz** [comment]
> Please merge this! this is a must for managing devices!!

Agreed - what do we need to do to get this over the line?

**Review by miquelbeltran — APPROVED** [review]

**Comment by miquelbeltran** [comment]
I resolved the merge conflicts, once CI finishes I will merge and release.

**Comment by miquelbeltran** [comment]
merged and published

**Comment by miquelbeltran** [comment]
This PR had to be reverted because the changes were not put in a major version, a new PR will come with the changes reapplied.

**Pull request merged**
