### PR TITLE
feat(battery_plus): Added aditional information on device battery

### PR DESCRIPTION
**Pull request by rktejesh**
## Description

Added additional methods to the present battery api to get device battery information such as Battery Capacity, Charging Status, Charge Time Remaining, Current Average, Current Now, Health, Plugged Status, Battery Presence, Scale, Remaining Energy, Technology, Temperature, Voltage.
This change has only been added to android. Other platforms are yet to be implemented

## Related Issues

This PR partially closes [#460](https://github.com/fluttercommunity/plus_plugins/issues/460)

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by miquelbeltran** [comment]
> This change has only been added to android. Other platforms are yet to be implemented

I would prefer that we don't add new functionality if it is not at least covering both Android and iOS (the two main platforms). Ideally with a plan to cover the six of them. Throwing a missing implementation exception leads to bad user experience. I already faced that with the `network_info_plus` missing some calls on MacOS for example.

We should probably clarify this in the CONTRIBUTING document.

Thoughts? @mhadaily @Elias8 @jpnurmi

**Comment by mhadaily** [comment]
Yes I agree @miquelbeltran I hope you can take care of it @rktejesh 

also build failed please double-check check formatting.

**Comment by miquelbeltran** [comment]
IMO if those values can only be retrieved for Android then I would encourage you to create an independent plugin for android specific functionality like `android_alarm_manager`, e.g. `android_battery_info`.

I will add the hacktoberfest tags but we cannot merge this PR I think.

**Comment by twogood** [comment]
@rktejesh did you ever follow through on this? Such a waste to throw away your Android work just because the other platforms are not yet implemented.

**Comment by rktejesh** [comment]
@twogood haven't given it much thought after that. Is it still viable to create this into a standalone plugin only for Android?

**Comment by twogood** [comment]
> @twogood haven't given it much thought after that. Is it still viable to create this into a standalone plugin only for Android?

Even if you don't want to maintain it, maybe just add it to its own GitHub repository somewhere.

**Pull request closed without merging**
