### PR TITLE
Redo changes in device_info_plus_platform_interface 2.6.0

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

- Revert "Revert 4.1.0 device_info_plus changes (#1020)"
- Version bumps

## Related Issues

https://github.com/fluttercommunity/plus_plugins/issues/939#issuecomment-1213044548

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Maybe we need to update all the dependencies of the macos, windows, linux and web federated plugins.

**Review by nohli — APPROVED** [review]
LGTM

**Comment by miquelbeltran** [comment]
> Maybe we need to update all the dependencies of the macos, windows, linux and web federated plugins.

so here's the catch:

- device_info_plus 4.1.2 depends on platform_inferface 3.0.0
- device_info_plus 4.1.2 depends on macos 2.2.3, that depends on platform_interface 2.2.0
- same issue for windows, linux and web

Would that be a problem? Should be bump all the versions of the other plugins to be on the safe side?

**Comment by miquelbeltran** [comment]
I don't trust having different dependencies, so I bumped all versions.

**Comment by nohli** [comment]
Thanks! This makes sure we have a stable release of everything.

**Review by nohli — APPROVED** [review]

**Pull request merged**
