### PR TITLE
fix: ClientException: Invalid content-length header [-1] when reading version.json on a Firefox extension

### PR DESCRIPTION
**Pull request by Chralu**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*

*e.g.*
- *Fix #123*
- *Related #456*

## Checklist

- [ ] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Hi @Chralu do you plan to do any changes here or can the PR be merged?

**Comment by Chralu** [comment]
Hi @miquelbeltran ,

my PR partially resolves the issue. We still encounter the `ClientException`, which is problematic.
Because of this, I would not recommand to merge it.

To completely resolve the issue, I see two options : 
1. Fix upstream [`http`](https://github.com/dart-lang/http/issues/1240) lib.
2. Use `Dio` instead of `http`.

Introducing a new dependency is a big deal, so I wonder what the core team thinks about it.

**Comment by miquelbeltran** [comment]
Or maybe this is a bug in Mozilla.

In either case, then let's close this PR, and when a proper solution is available create a new one.

**Comment by miquelbeltran** [comment]
As mentioned, I will close this PR for the time being until a complete solution to the mozilla extensions is found. We continue the discussion here: https://github.com/fluttercommunity/plus_plugins/issues/3028

**Pull request closed without merging**
