### PR TITLE
[device_info_plus] added support for android background platform channels

### PR DESCRIPTION
**Pull request by gaaclarke**
## Description

Made device_info execute on background platform channels when it is available instead of managing its own thread.

There is no new functionality and executing tests against the master channel and the stable channel will exercise both variants of the code.

## Related Issues

b/203709390
issue: https://github.com/flutter/flutter/issues/91635

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mhadaily** [comment]
thanks, what do you think about this @miquelbeltran and @jpnurmi ?

**Comment by miquelbeltran** [comment]
This is an interesting approach but I fail to see the advantages (at least they are not obviously stated in the original ticket) plus doesn't seem to be stable yet, right? I'd rather hold on this one.

**Comment by jpnurmi** [comment]
Thanks for supporting us! :) Offloading to a worker thread sounds useful so +1 from me.

**Comment by gaaclarke** [comment]
Sorry, a lot of the information informing this is in a google issue.  There is the design doc you should see that should explain it (linked in the linked issue).  The gist is that apps that use a lot of plugins can pound the platform thread.  This can be particularly bad at app launch.  We had a google customer that was querying device_info during startup and while the execution of device_info is fast, it is taking hundreds of milliseconds because of a logjam on the platform thread.

This isn't in stable yet, that is why it is guarded behind reflection.  You won't be using it unless it is available, which means you are on an "unstable" version of flutter.

**Review by piotrsed — APPROVED** [review]

**Comment by vbuberen** [comment]
@gaaclarke It is quite a lot of time passed since this PR was opened, but what is the status of changes? These changes are already available in stable?

**Comment by gaaclarke** [comment]
Yep they are available on stable.

**Comment by vbuberen** [comment]
Great. In such case could you update your PR?

**Comment by gaaclarke** [comment]
> Great. In such case could you update your PR?

done!

**Comment by vbuberen** [comment]
@gaaclarke Could I ask you to address the feedback, so we can finally merge this PR?

**Comment by miquelbeltran** [comment]
Hey! Due to changes in our contributor guidelines, all PRs should now:

- Have a title that follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) format. e.g. `feat(package_name)!: feature description`
- **DO NOT** modify the CHANGELOG.md or the version in the `pubspec.yaml`. This is going to be an automated process now.

We would ask you kindly to update the PR following these changes.

Thanks!

**Comment by vbuberen** [comment]
I think it can be closed as there is no activity for quite some time already.

**Pull request closed without merging**
