### PR TITLE
fix(package_info_plus): fixed deprecation warning & updated dependencies

### LINKED ISSUE #301: Production app bundle build warning uses or overrides a deprecated API.
## System info

Issue occurs on:  Android
Plugin name: package_info_plus
Plugin version:  ^1.0.1

## Steps to Reproduce

`flutter build appbundle`

```
 Building with sound null safety 

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info_plus-1.0.1\android\src\main\java\dev\fluttercommunity\plus\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

## Logs

[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale bg-BG)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\SDK
    • ANDROID_SDK_ROOT = C:\Android\SDK
    • Java binary at: C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • android-studio-dir = C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\Mike\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!

### PR DESCRIPTION
**Pull request by juliansteenbakker**
## Description

This PR removes the deprecated embedding V1 from package_info_plus. Besides that it updates the dependencies and fixes a deprecation issue with regards to `getBuildSignature` method.

## Related Issues

Probably fixes #301 

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mhadaily** [comment]
I just updated main branch can you please  update with `main`. and then let's merge your branch.

**Comment by juliansteenbakker** [comment]
> I just updated main branch can you please update with `main`. and then let's merge your branch.

I will but before merging, should we remove the deprecated registerwith function, or just leave it in and annotate so it hides the warning? Because whatever we chose, we should apply it to all other packages aswell.

**Comment by mhadaily** [comment]
Well, I'd say if we have a solution to replace it with a new API, let's do that, that much better, however, if we don't lets at least annotate it so later we will remove depreciated API and replace them with a new one. 

I prefer to implement a new API if possible.

**Comment by juliansteenbakker** [comment]
Currently v1 embedding with `registerWith` is only kept for backwards compatibility. However it seems that it isn't included in new releases according to official Flutter documentation. So i'd say it's safe to remove it.

**Comment by nohli** [comment]
@juliansteenbakker
It is my understanding that it is good to keep the registerWith() method to remain compatible:

`Also, note that the plugin should still contain the static registerWith() method to remain compatible with apps that don’t use the v2 Android embedding. (See Upgrading pre 1.12 Android projects for details.) The easiest thing to do (if possible) is move the logic from registerWith() into a private method that both registerWith() and onAttachedToEngine() can call. Either registerWith() or onAttachedToEngine() will be called, not both.`

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration#upgrade-steps

@mhadaily
I added PRs that suppress the build warnings for all remaining packages. Didn't see that for package_info_plus there is already this one. I can close mine probably?

**Comment by juliansteenbakker** [comment]
@nohli It's more a question of choice i think. The flutter team encourages everyone to upgrade to V2, and right now only 20% of the projects use V1. You can keep providing support for V1 but where are you going to draw the line? Besides that, is it even possible for Flutter applications that only support V1 embedding to also support null-safety, like all packages here does?

**Comment by juliansteenbakker** [comment]
@nohli You can close your pr for this package. I'll update this to leave the registerWith in it if thats what we're deciding.

**Comment by mhadaily** [comment]
@nohli @juliansteenbakker let's discuss there and make a decision, I don't think it's very critical to support V1. what we can do we can remove this and release a new Major version for packages so if anyone likes to use older version so still, they can but we will not support it? 

what do you think?  

question for you @nohli  if you think this PR is covering your PRs, let's close yours and focus on this one if you agree?

**Comment by mhadaily** [comment]
@juliansteenbakker build failed, I think you need to rebase with `main`

**Comment by nohli** [comment]
Already closed.

So you want me to close all the other PRs, and open a new one, removing the registerWith method, for all other packages?

**Comment by mhadaily** [comment]
I am not still sure if removing registerWith() is a correct way of doing it. however, if we release a new Major version, it won't break people's code. 

btw, since this change is fairly similar for all packages, I'd like to have one PR covering the same thing for all packages instead of several PRs. 

just in case if we got any problem, I can revert one commit and it works for all packages at the same time. 

What's your opinion @nohli and @juliansteenbakker ? I'd like to know your opinion too.

**Comment by juliansteenbakker** [comment]
> What's your opinion @nohli and @juliansteenbakker ? I'd like to know your opinion too.

In my opinion i think it's good to just delete them. People using embedding v1 should upgrade, even the Google documentation says so. This in combination with new plugins being created without embedding v1 is enough reason for me to remove it.

I can however understand that other people would keep embedding v1 in 'just in case' and i think it's a valid point, but it's just not my opinion.

**Comment by juliansteenbakker** [comment]
As discussed in #461 i've deleted the v1 embedding once again and bumped the version number. 

Currently blocked by #489

**Comment by mhadaily** [comment]
@juliansteenbakker PR is merged. 

btw, since we have now this PR https://github.com/fluttercommunity/plus_plugins/pull/495 do you think your PR will be still valid?

**Comment by juliansteenbakker** [comment]
> btw, since we have now this PR #495 do you think your PR will be still valid?

Yes because that PR doesn't contain changes for package_info_plus. Also, this PR solves other deprecation problems besides embedding V1.

**Comment by juliansteenbakker** [comment]
@mhadaily this is ready to be merged

**Comment by nohli** [comment]
@juliansteenbakker could you also use `30` for `compileSdkVersion` and `targetSdkVersion`?
31 is Android 12 which is still in beta.

**Comment by vbuberen** [comment]
> 31 is Android 12 which is still in beta.

It is not in beta since yesterday, but I would be careful with pushing to 31, because it has some behavior changes. For example, `android_alarm_manager` should be upgraded carefully, considering this change https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission 
Haven't checked if other packages would need the same though

**Comment by juliansteenbakker** [comment]
@nohli Android 12 is not in beta anymore. Besides, when a new number is available in `compileSdkVersion`, it means that the API is stable. [Otherwise it would be marked as such: `compileSdkVersion 'android-R'`](https://stackoverflow.com/a/60389520/13031778). [`compileSdkVersion 31` has been stable since 14 July.](https://android-developers.googleblog.com/2021/07/android-12-beta-3.html)

**Comment by juliansteenbakker** [comment]
> > 31 is Android 12 which is still in beta.
> 
> It is not in beta since yesterday, but I would be careful with pushing to 31, because it has some behavior changes. For example, `android_alarm_manager` should be upgraded carefully, considering this change https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission Haven't checked if other packages would need the same though

We should migrate and check every package individually. That is why this PR is only about package_info_plus.

**Comment by vbuberen** [comment]
> We should migrate and check every package individually

Yes, agree here. My message was mostly to @nohli since he has one big PR with changes to multiple packages, so I wanted to bring attention to that moment about Android 12.

**Review by miquelbeltran — APPROVED** [review]
LGTM!

**Comment by miquelbeltran** [comment]
no particular reason, we are just a bit overwhelmed at the moment, but I am trying to get as much PRs merged as possible

**Pull request merged**
