### PR TITLE
chore(release): prepare for release

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

Release PR

## Related Issues

None

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Can't approve my own PRs but the versions and changelogs lgtm

**Review by vbuberen — APPROVED** [review]
Looks good to me.

As to failing tests for `connectivity_plus` - they were failing on API 21 when I added the build matrix recently: https://github.com/fluttercommunity/plus_plugins/actions/runs/3244740489

Will address it soon.

**Comment by miquelbeltran** [comment]
Thanks! I will continue with the release process then.

**Comment by zeewell** [comment]
Hi, @miquelbeltran @vbuberen 

There is a compile error here https://github.com/fluttercommunity/plus_plugins/issues/1259, when is the estimated time to release a new version of connectivity_plus_platform_interface?

**Comment by vbuberen** [comment]
> There is a compile error here #1259, when is the estimated time to release a new version of connectivity_plus_platform_interface?

What is the point of tagging people? There were no new features or critical fixes introduced in the 3.0.0 release. There is already a bug report, so just use older version of the plugin and don't tag people multiple times.

**Pull request merged**
