### PR TITLE
All pubspec.yaml include homepage and repository

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

Solves https://github.com/fluttercommunity/plus_plugins/issues/15

Adds this to all public pubspec.yaml (not including example projects)

```
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
```

## Related Issues

https://github.com/fluttercommunity/plus_plugins/issues/15

### CODE REVIEW

**Comment by jpnurmi** [comment]
Should the repo link point to the tree? https://github.com/fluttercommunity/plus_plugins/tree/main/packages

https://github.com/fluttercommunity/plus_plugins/packages/ points to GitHub packages:

image

**Comment by miquelbeltran** [comment]
ugh that's bad, let me fix that

**Review by jpnurmi — APPROVED** [review]
Nice!

**Comment by miquelbeltran** [comment]
I went ahead and merged this. If we decide to change the homepage URL let's do a quick search and replace.

**Pull request merged**
