### PR TITLE
Consider 4g network as mobile network instead of wifi on web platforms

### LINKED ISSUE #383: connectivity_plus always showing ConnectivityResult.wifi on web, even when WiFI is switched off
## System info

Issue occurs on: Web
Plugin name: connectivity_plus
Plugin version: 1.0.6

## Steps to Reproduce

Running on Chrome browser, when connectivity state changes (I toggle Wifi), `onConnectivityChanged()` get called every time, but the enum value of ConnectivityResult always returns `ConnectivityResult.wifi`.

I tested the same in android, it works fine (shows `ConnectivityResult.none` while WiFI is turned off)

### PR DESCRIPTION
**Pull request by Elias8**
## Description

In the current web platform implementation `4g` network is considered as `wifi`, but as mentioned [here](https://wicg.github.io/netinfo/#underlying-connection-technology-0) on the `Network Information API` documentation, 4g should be considered as a cellular network. So, this pr fixes that.

## Related Issues

Closes #383

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by Elias8** [comment]
As this PR could be a temporary solution, using [NetworkInformation.type](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type) would be the better way for this implementation as @jpnurmi mentioned it [here](https://github.com/fluttercommunity/plus_plugins/issues/383#issuecomment-890145200).

**Review by mhadaily — APPROVED** [review]
LGTM, thanks

**Comment by mhadaily** [comment]
@Elias8  can you please update CHANGELOG and pump a  patch version of the package? and push again

**Comment by Elias8** [comment]
Done!

**Pull request merged**
