### PR TITLE
Add ethernet as connectivity result

### PR DESCRIPTION
**Pull request by jpnurmi**
So far, implemented for Android, Linux, and Web.

### CODE REVIEW

**Comment by mhadaily** [comment]
@jpnurmi This looks good to me, but what do you want to do for Web and iOS, and Windows? should we just return null or an error?

**Comment by jpnurmi** [comment]
Android, Linux, and Web have been implemented. I also have a working prototype for macOS, but it will follow in a separate PR. On iOS, we can probably use the same.

So basically the only remaining platform is Windows, and it seems to be a real pain. Perhaps we can get some Windows expert to help with that.

**Review by mhadaily — APPROVED** [review]
LGTM

**Comment by mhadaily** [comment]
We have another PR related to connectivity, Maybe we should merge this after that one. although they are not related.

**Comment by mhadaily** [comment]
@jpnurmi feel free to resolve conflict and merge and release.

**Comment by Elias8** [comment]
I think this closes #279

**Pull request merged**
