### PR TITLE
[package_info_plus] Added supported platforms to README.md

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

When I read the `README.md` of `package_info_plus` it wasn't for me clear, which platforms are supported. You can see it maybe with the dependencies like `package_info_plus_linux`. However, it is very hidden. And in the description of the `pubspec.yaml`, which will be displayed at the right side, mentioning only Android & iOS which is confusing (My thoughts: Why not also mention Linux, Web, macOS and Windows? Or is there no support for this platforms)? 

## Demo
image

## Related Issues
Part of #111

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by nilsreichardt** [comment]
Should I also add the other packages to this PR or should I split it in many small PRs (like this PR)?

**Comment by miquelbeltran** [comment]
@nilsreichardt I don't mind either way, however works best for you!

Also @pr-Mais was planning to do this, you should coordinate so you are not doing the work twice.

**Review by miquelbeltran — APPROVED** [review]

**Comment by pr-Mais** [comment]
@nilsreichardt thanks for the PR, I was just thinking of doing one, you can add the supported platforms for all of them, I will be working on adding more examples, so we won't conflict each others.

**Comment by nilsreichardt** [comment]
@pr-Mais I you want you take over. I did this for `package_info_plus` so I cloud create a screenshot for #111.

**Comment by pr-Mais** [comment]
@nilsreichardt alright I will continue for the rest, thanks!

**Comment by nilsreichardt** [comment]
@pr-Mais Great! Maybe you can assign yourself to #111, so other people see that you doing this ticket.

**Comment by pr-Mais** [comment]
@nilsreichardt done :)

**Comment by miquelbeltran** [comment]
@pr-Mais I will merge this one meanwhile, you will have to create a new PR for the rest.

**Comment by pr-Mais** [comment]
@miquelbeltran noted

**Pull request merged**
