### PR TITLE
make toMap() json compatible

### LINKED ISSUE #949: [Request]: make toMap() json compatible
### Plugin

device_info_plus

### Use case

renaming `toMap()` as `toJson` would improve compatibility with `dart:convert` 
see referece at https://api.dart.dev/be/175791/dart-convert/jsonEncode.html

> If toEncodable is omitted, it defaults to a function that returns the result of calling .toJson() on the unencodable object.

### Proposal

rename BaseDeviceInfo method toMap() as toJson() and to all overrides across the package

### PR DESCRIPTION
**Pull request by Yczar**
## Description

*Rendered toMap on the models to be jsonCompatible*

## Related Issues

* fix #949 

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by miquelbeltran** [comment]
An `@overrides` is missing, check the analyze output.

Would it be possible to add unit tests for the toJson methods?

**Comment by Yczar** [comment]
> An `@overrides` is missing, check the analyze output.
> 
> Would it be possible to add unit tests for the toJson methods?

Fixed this in the new push @miquelbeltran

**Comment by Yczar** [comment]
> An `@overrides` is missing, check the analyze output.
> 
> Would it be possible to add unit tests for the toJson methods?

Fixed these on the latest push @miquelbeltran

**Comment by iapicca** [comment]
@miquelbeltran 
shouldn't "toJson" return a json rather than a string?

**Comment by Yczar** [comment]
> @miquelbeltran shouldn't "toJson" return a JSON rather than a string?

toJson should return a parseable string otherwise it is just toMap with a change of name. @iapicca

**Comment by iapicca** [comment]
> > @miquelbeltran shouldn't "toJson" return a JSON rather than a string?
> 
> toJson should return a parseable string otherwise it is just toMap with a change of name. @iapicca

I'm saying that this PR doesn't the issue you linked 
the current problem is that `toMap` breaks dart:convert as it returns an `enum` somewhere

I fixed in this [PR](https://github.com/fluttercommunity/plus_plugins/pull/950), 
but I didn't get any answer in 2 months

your approach seems to be adding a `toJson` method rather than fixing `toMap`
similar approach as been previously described as [not needed](https://github.com/fluttercommunity/plus_plugins/pull/950#issuecomment-1185264150) by @vbuberen

and [quoting](https://github.com/fluttercommunity/plus_plugins/pull/950#issuecomment-1187329379) @miquelbeltran 

> I am sorry, I am not sure anymore if we need this. If a user wants to serialize the contents of a `DeviceInfo` object, they should do it on their own app data model. We shouldn't be maintaining a `toJson` implementation on our side, even if convenient, it is not our job. Like, I am not even sure why are we providing a toMap method even, I guess that's the legacy from when we got the plugins from Google.

**Comment by Yczar** [comment]
> > > @miquelbeltran shouldn't "toJson" return a JSON rather than a string?
> > 
> > 
> > toJson should return a parseable string otherwise it is just toMap with a change of name. @iapicca
> 
> I'm saying that this PR doesn't the issue you linked the current problem is that `toMap` breaks dart:convert as it returns an `enum` somewhere
> 
> I fixed in this [PR](https://github.com/fluttercommunity/plus_plugins/pull/950), but I didn't get any answer in 2 months
> 
> your approach seems to be adding a `toJson` method rather than fixing `toMap` similar approach as been previously described as [not needed](https://github.com/fluttercommunity/plus_plugins/pull/950#issuecomment-1185264150) by @vbuberen
> 
> and [quoting](https://github.com/fluttercommunity/plus_plugins/pull/950#issuecomment-1187329379) @miquelbeltran
> 
> > I am sorry, I am not sure anymore if we need this. If a user wants to serialize the contents of a `DeviceInfo` object, they should do it on their own app data model. We shouldn't be maintaining a `toJson` implementation on our side, even if convenient, it is not our job. Like, I am not even sure why are we providing a toMap method even, I guess that's the legacy from when we got the plugins from Google.

All checks passed on this end... I feel we should leave it to the regulators to decide which approach is right or wrong... I noticed the enum was redundant Because there is already a function and a getter that generates the enum in the first place. So there was never a need for the breaks to happen. But if the maintainers find your approach interesting then I believe they would do the justice.

**Comment by miquelbeltran** [comment]
@iapicca sorry, I forgot that we had your PR on this, I apologize for not having followed up.

Since the original issue has been closed, I will simply close this PR as well.

As I though originally, I am not in favor of adding extra functionality to the plugins that should be external to the plugin, like JSON support.

**Comment by vbuberen** [comment]
> similar approach as been previously described as not needed by @vbuberen

Would be good if you could calm down a little bit first, because seems like the miscommunication issue and lack of response from the reviewer of your PR made you feel offended.

Secondly, I wasn't stating anything there, but was genuinely curios to find out what is the reason behind your changes. So would be also good to understand that such question might have a different meaning than what you implied.

**Pull request closed without merging**
