### PR TITLE
[sensors_plus] migrate to null-safety (#50)

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Review by mhadaily — DISMISSED** [review]
So far it looks good to me

**Comment by jpnurmi** [comment]
Wait, what's the correct version?

`0.6.0` => `0.7.0-nullsafety.0` or `1.0.0-nullsafety.0`?

**Comment by mhadaily** [comment]
I think major version is expected so 1.0.x

**Comment by jpnurmi** [comment]
> I think major version is expected so 1.0.x

Ok, thanks! Done :)

**Review by miquelbeltran — APPROVED** [review]
Thanks!

**Pull request merged**
