### PR TITLE
feat(share_plus): Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by charafau**
ref: https://github.com/fluttercommunity/plus_plugins/issues/3152

Another spm support

### CODE REVIEW

**Review by miquelbeltran — COMMENTED** [review]
LGTM, I still want to check on my devices before approval and merge

**Comment by vbuberen** [comment]
Edited the title and will do for the rest of PRs as there is already a scope in braces defined.

**Comment by charafau** [comment]
> Edited the title and will do for the rest of PRs as there is already a scope in braces defined.

Thank you 🙏  will try better next time

**Review by vbuberen — APPROVED** [review]
Did a few small fixes, but overall everything works fine on iOS and MacOS.

Thanks for your contribution!

**Pull request merged**
