### PR TITLE
Fix [android_alarm_manager_plus] AndroidAlarmManager.periodic() not working.

### PR DESCRIPTION
**Pull request by aakash-pamnani**
## Description

setPerioidic was not working due to parameter sequence was not correct.

and if less than 60 sec interval given android will make it default to 60 sec
this is what i got from log
image

## Related Issues

#787
#709

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by aakash-pamnani** [comment]
is there anything wrong in my pull request
I am a beginner and learning , please let me know if anything is wrong.

**Comment by Andrew-Bekhiet** [comment]
Any update on this?

**Comment by Andrew-Bekhiet** [comment]
I don't understand why no one has approved this simple yet critical fix

**Comment by aakash-pamnani** [comment]
> I don't understand why no one has approved this simple yet critical fix
Yes ,its been more than 2 months now still no response from reviewer.

**Comment by vbuberen** [comment]
> I don't understand why no one has approved this simple yet critical fix

Because Plus Plugin are an open source project, which people maintain in their free time for free. It is not a commercial product where somebody charges some licences fees, etc. to complain this way. 

It will be reviewed when it will be reviewed. If it is something that critical for you it would be better to test the fix and provide feedback if it really changes something in the meantime instead of just writing `Any update on this`. This way it would be more constructive way on helping to move forward than writing such messages.

**Comment by Andrew-Bekhiet** [comment]
> Because Plus Plugins is an open source project, which people maintain in their free time for free. It is not a commercial product where somebody charges some licences fees, etc. to complain this way.

I'm sorry if I seemed a little aggressive on this

> If it is something that critical for you it would be better to test the fix and provide feedback

I've tested it since I've seen it for the first time, and it fixes this bug that has bothered me for about a month before I saw the pr

**Comment by vbuberen** [comment]
> I've tested it since I've seen it for the first time, and it fixes this bug that has bothered me for about a month before I saw the pr

Thanks for your feedback. I will try to get to this PR this week and test/review as well.

**Review by vbuberen — APPROVED** [review]
Checked the change and it looks like it is really a fix, since there was a typo with wrong order of parameters. Also did some testing on a few emulators and real devices with different Android versions and can confirm that this change fixes the `periodic` alarm.

Thanks for your contribution.

Might also be a fix for #901 and #871 

Closes #787 and #709

**Comment by miquelbeltran** [comment]
release 2.0.6 published, thanks everyone for getting into this!

**Comment by carman247** [comment]
Still doesn't work ...

**Pull request merged**
