### PR TITLE
feat(sensors_plus)!: Migrate to dart:js_interop

### LINKED ISSUE #2602: [Request]: (sensors_plus) Migrate to `package:web` to support WASM
### Plugin

sensors_plus

### Use case

Compiling to WASM

### Proposal

The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

### PR DESCRIPTION
**Pull request by koji-1009**
## Description

APIs such as Accelerometer are defined independently using dart:js_interop.

---

Do you know how to see the sensor change in the browser, I tried emulation with chrome dev tools but could not see the value change.

https://developer.chrome.com/docs/devtools/sensors

## Related Issues

- Resolve #2602

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by koji-1009** [comment]
Thanks for the quick response!
I checked `web` and the Sensor API type does not exist. For this reason, I am not using `web` 👍

**Comment by miquelbeltran** [comment]
Similar errors, slightly different, on macOS + Chrome:

`main`

```
[log] Magnetometer() is not supported by the User Agent.
[log] The linear acceleration API is supported but something is wrong!
[log] The gyroscope API is supported but something is wrong!
```

The PR code:

```
[log] Magnetometer() is not supported by the User Agent.
[log] TypeError: constr is not a constructor
[log] The linear acceleration API is supported but something is wrong!
[log] Could not connect to a sensor
[log] The gyroscope API is supported but something is wrong!
[log] Could not connect to a sensor
```

In theory, it is all well-supported in chrome, but I have the sensation it never worked before.

Looking at the documentation https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs we are supposed to query for permissions, but that doesn't seem to happen here at all.

image

"could not connect to a sensor" is the only error visible.

**Comment by koji-1009** [comment]
Thank you!
I will try to get the permissions. If it works, I'll add a new commit.

**Comment by koji-1009** [comment]
hmm, I tested following codes. The permissions are already granted.

```dart
import 'package:web/web.dart';

~~~

@override
Stream<AccelerometerEvent> accelerometerEventStream({
  Duration samplingPeriod = SensorInterval.normalInterval,
}) {
  if (_accelerometerStreamController == null) {
    _accelerometerStreamController = StreamController<AccelerometerEvent>();
    _featureDetected(
      () async {
        final status = await window.navigator.permissions
            .query(
              PermissionDescriptor(
                name: 'accelerometer',
              ),
            )
            .toDart;
        print('accelerometer: name: ${status.name}, state: ${status.state}');

```

result.

```
accelerometer: name: sensors, state: granted
```

I will continue to investigate.
The js_interop is interesting.

**Comment by miquelbeltran** [comment]
Great job! Checked on my phone and it works as well. Is the code in the PR up-to-date?

**Comment by koji-1009** [comment]
Yes, the PR code is up to date.
When deploying the demo, `/sensors_plus/example/web/index.html` needs to be newer, so it is updated. However, there are no additional changes in `/sensors/lib`.

https://github.com/koji-1009/plus_plugins/pull/1/files#diff-c8f651872a9b98a8388ebdbbe12c950e1ae16e5d62c746cbd71192524b9b058a

**Review by miquelbeltran — APPROVED** [review]

**Comment by koji-1009** [comment]
Thanks!

**Comment by miquelbeltran** [comment]
Thanks to you!

**Comment by guibertjulien** [comment]
Hello, I have this log with sensors_plus 6.0.0 with Chrome, is it normal ? I try to test sensor with a PWA application.
Capture d’écran 2024-08-05 à 08 24 32

**Pull request merged**
