### PR TITLE
[device_info_plus] update versions for publishing

### LINKED ISSUE #646: [device_info_plus] UnimplementedError when fetching info on Linux
I started getting the following exception after updating `device_info_plus` from `2.0.0` to `3.1.1`:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: UnimplementedError: linuxInfo() has not been implemented.
#0      DeviceInfoPlatform.linuxInfo (package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart:69:5)
#1      DeviceInfoPlugin.linuxInfo (package:device_info_plus/device_info_plus.dart:58:50)
[…]
```

It seems to be a regression since downgrading to `2.0.0` works as expected.

## System info

Issue occurs on: Linux
Plugin name: device_info_plus
Plugin version: 3.1.1
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on Fedora Linux 35 (Workstation Edition)
    5.15.6-200.fc35.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by alexbatalov**
## Description

Right now using published versions of `device_info_plus` on Windows and Linux fails with Flutter 2.8.1. #574 and #598 needs publishing. Fixes #646.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by nohli — APPROVED** [review]

**Comment by mhadaily** [comment]
@nohli should we merge this and release it? if so, then how about this one? https://github.com/fluttercommunity/plus_plugins/pull/671

**Comment by nohli** [comment]
@mhadaily I would merge it. Since the other PR is just updating the changelog for changes that are already merged, I will then rebase it, so it can be merged, and then we release a new version including all PRs? What so you think?

**Comment by mhadaily** [comment]
@nohli  Happy new year too! sounds good. let's do it

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
