### PR TITLE
[network_info_plus] Fix issue #431 network_info_plus: 'net/route.h' file not found when building for iOS emulator

### PR DESCRIPTION
**Pull request by phan-dev**
## Description
Fix issue #431 network_info_plus: 'net/route.h' file not found when building for iOS emulator

## Related Issues
#431 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by phan-dev** [comment]
#431

**Review by lucasratske — APPROVED** [review]

**Comment by phan-dev** [comment]
@lucasratske 
Thank you for approval!
But there are some checks were cancelled. How can we re-run them again?

**Comment by diegotori** [comment]
@lucasratske can we prioritize this issue since I can't build my app that uses this library with Flutter 2.5? Thanks in advance.

**Comment by diegotori** [comment]
@mhadaily Sorry to be a bother, but this one should also be added to the next release urgently. Thanks in advance.

Also, if you're in need of someone to release builds, add me on pub.dev at diegotoridoesandroid@gmail.com. I'm willing to help release builds to spread out the burden if you want.

**Review by mhadaily — APPROVED** [review]
LGTM

**Comment by mhadaily** [comment]
@phan-dev, can you please add a CHANGELOG and bump a path version for network_plus_info? I'll merge and release after that. 

Thank you for the PR

**Comment by phan-dev** [comment]
@mhadaily 
Thank you for review!
Do you mean I add CHANGELOG for the new version 1.1.1 ?

**Comment by mhadaily** [comment]
yes please 

here https://github.com/fluttercommunity/plus_plugins/blob/main/packages/network_info_plus/network_info_plus/CHANGELOG.md

**Review by mhadaily — APPROVED** [review]

**Comment by phan-dev** [comment]
@mhadaily 
Thank you!

**Pull request merged**
