### PR TITLE
Update/device info plus

### PR DESCRIPTION
**Pull request by nohli**
## Description

Bump version, so https://github.com/fluttercommunity/plus_plugins/pull/588 can be published.

## Related Issues
https://github.com/fluttercommunity/plus_plugins/issues/569

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by vbuberen — APPROVED** [review]

**Review by vbuberen — CHANGES_REQUESTED** [review]
I believe there is another PR, which clashes with this one https://github.com/fluttercommunity/plus_plugins/pull/663

**Comment by nohli** [comment]
The changes of this PR are already committed. Should we rather merge this PR, rebase the other PR and update its version?

**Comment by vbuberen** [comment]
@nohli Since #623 and #663 were opened earlier I would merge them first and update your PR afterwards.

**Comment by mhadaily** [comment]
@nohli once this is ready, let's merge this and then release a new package.

**Comment by nohli** [comment]
@mhadaily should we merge this one, too?
https://github.com/fluttercommunity/plus_plugins/pull/623

**Comment by mhadaily** [comment]
> @mhadaily should we merge this one, too? #623

yes, but it has conflicts now, unfortunately. I can resolve the conflict but I am not sure what I should change to fix it, do you know?

**Comment by nohli** [comment]
@mhadaily I can't see the conflicting file, or resolve the conflict, but it should be the changelog. Can you edit it and merge the `3.2.1` changes from main and https://github.com/fluttercommunity/plus_plugins/pull/623/files?

**Comment by mhadaily** [comment]
I have fixed the conflicts, https://github.com/fluttercommunity/plus_plugins/pull/623/files, 

@nohli , please make sure in this PR we have all changelogs and versions properly in place, so then after this PR, I can lease one version.

**Comment by nohli** [comment]
@mhadaily done

**Comment by mhadaily** [comment]
@nohli other PR was merged too. please take a final look and then wait for build to complete, then I will merge if looks good to you and me and then I will release. sounds good?

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
