### PR TITLE
feat(connectivity_plus)!: Migrate to package:web

### LINKED ISSUE #2600: [Request]: (connectivity_plus): migrate to pkg:web from dart:html
### Plugin

connectivity_plus

### Use case

Flutter web apps are required to migrate from `dart:html` to `package:web` to use WASM.

### Proposal

This issue tracks the upgrade process for `connectivity_plus`.

See https://docs.flutter.dev/platform-integration/web/wasm and https://pub.dev/packages/web for more information

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

- Replace calls to `dart:html` by the equivalent with the `package:web`.
- Tested on Chrome + macOS
- Set `web` version to `>=0.3.0 <=0.6.0` to be backwards compatible.
- Set min Dart sdk version to 3.2.0 in package, as it is the min version of web 0.3.
- Removed unused `NetworkInformationApiConnectivityPlugin` with the `js` dependency.

## Related Issues

- Closes #2600 

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

Potentially a breaking change, since it will require new `package:web` dependencies.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
The `connectivity_plus` class `NetworkInformationApiConnectivityPlugin` is not even used. I am considering removing it.

**Comment by vbuberen** [comment]
> The connectivity_plus class NetworkInformationApiConnectivityPlugin is not even used. I am considering removing it.
Great finding. Sure, let's remove it along with `js` dependency.

**Review by vbuberen — APPROVED** [review]
Now looks good to me with range and Dart version bump.
Thanks for taking care of it.

**Review by vbuberen — APPROVED** [review]

**Comment by vbuberen** [comment]
Looks like it also closes #2598

**Pull request merged**
