### PR TITLE
fix: stream fallback for unsupported browsers

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
- add a periodic fallback checking the current online state in case `external navigator.connection` is unavailable

## Description

When trying to access `Connectivity().onConnectivityChanged` on browsers without support for `navigator.connection`, there's simply an error thrown.

This PR means to workaround this by calling `@JS("navigator.connection")` to ensure the API is supported. In case not, a periodic timer takes care of not-that up to date connection information.

## Related Issues

?

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by piotrsed — APPROVED** [review]

**Comment by TheOneWithTheBraid** [comment]
Is anyone willing to review and approve this PR?

**Comment by TheOneWithTheBraid** [comment]
Is anyone willing to merge? This is a must-have in order to properly support web.

**Comment by TheOneWithTheBraid** [comment]
It feels like the connectivity plugin is no longer maintained. Is anyone willing to review this PR?

**Review by miquelbeltran — APPROVED** [review]
Sorry we dropped this, I am checking it out and will be merged and published in short

**Pull request merged**
