### PR TITLE
fix(all): Increase min Flutter version to fix dartPluginClass registration

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

Fixes the issue where the `dart_plugin_registrant.dart` file is not generated correctly.

Tested this locally with packages referenced by path. When I increased the Flutter SDK version to 2.11 then the issue we saw in #1270 was gone.

## Related Issues

- Fix: https://github.com/fluttercommunity/plus_plugins/issues/1270
- Related: https://github.com/flutter/flutter/pull/96610
- Related: https://github.com/flutter/flutter/issues/113720
- Related: https://github.com/fluttercommunity/plus_plugins/issues/1274

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Since we are at it, I have also upgraded the platform interfaces (although not required for this fix) and removed some of the SDK requirements from the examples, as they are not required.

**Comment by CodeDoctorDE** [comment]
Why do we need the platform_interface packages if there is only one package for everything?

**Comment by miquelbeltran** [comment]
> Why do we need the platform_interface packages if we only need one package for every platform?

It has been a long discussion in the maintainers team, and the conclusion is that having a package interface as an external package allows for expandability. I'd personally get rid of it but not everyone agreed.

**Review by vbuberen — APPROVED** [review]
This is great that we are pushing things a little bit and getting rid of these really old versions as well as bumping all plugins at once, getting rid of differences in min supported version.

**Pull request merged**
