### PR TITLE
[ci] Setup flutter-action based CI

### PR DESCRIPTION
**Pull request by jpnurmi**
Runs tests on multiple platforms and collects coverage.

### CODE REVIEW

**Comment by jpnurmi** [comment]
Codecov integration needs to be enabled for the repo, and CODECOV_TOKEN secret needs to be defined.

**Comment by jpnurmi** [comment]
Coverage is currently around 69%.

Tested with my personal fork:

image

**Review by miquelbeltran — APPROVED** [review]
This is great! thanks for cleaning up the CI scripts as well and removing the old ones. An almost coverage of 70% is actually not that bad :)

**Comment by miquelbeltran** [comment]
We can also add the Codecov shield to the README.md :)

```
![Codecov](https://img.shields.io/codecov/c/gh/fluttercommunity/plus_plugins)
```

**Comment by jpnurmi** [comment]
@mhadaily The CI needs some updates:
- Codecov integration needs to be enabled for the repo
- CODECOV_TOKEN secret needs to be defined
- The required jobs need to be updated

**Comment by mhadaily** [comment]
@jpnurmi DMed you. thank you this looks amazing. nice charts. Will this aggregate all data from all packages? how does it work?

**Review by mhadaily — APPROVED** [review]
Fantastic!

**Comment by jpnurmi** [comment]
> Will this aggregate all data from all packages?

codecov-action had support for building multiple lcov files:

image

Must be also possible to configure it so that each package would have its own coverage, but this is a good start I think. :)

**Pull request merged**
