### PR TITLE
contrib: flutter_plugin_tools not needed

### PR DESCRIPTION
**Pull request by bruno-garcia**
## Description

"refactoring" the contributing guideline.
`flutter_plugin_tools` [was discontinued](https://pub.dev/packages/flutter_plugin_tools) and it's not needed to contribute to this repository.

Glad to amend this PR further if more items are outdated, so review appreciated.

### CODE REVIEW

**Comment by jpnurmi** [comment]
What about `melos.yaml`?

```
$ git grep flutter_plugin_tools
melos.yaml:  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
melos.yaml:  format: pub global run flutter_plugin_tools format
```

**Comment by bruno-garcia** [comment]
> What about `melos.yaml`?
> 
> ```
> $ git grep flutter_plugin_tools
> melos.yaml:  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
> melos.yaml:  format: pub global run flutter_plugin_tools format
> ```

Good point. I hope it has no difference in formatting from `flutter format` and we can just replace it with that.

What we discussed about a bot that pushes formatted code into the PR (as opposed to failing CI to and wait the author to do that) could rely on `flutter format` too. What do you think?

**Comment by jpnurmi** [comment]
Sounds great! Doesn't `flutter format` format only Dart files, though? I recall `flutter_plugin_tools` uses `clang-format` to format all the native code too, including Java, C++ etc.

**Comment by bruno-garcia** [comment]
> Automatic formatting sounds great! Doesn't `flutter format` format only Dart files, though? I recall `flutter_plugin_tools` uses `clang-format` to format all the native code too, including Java, C++ etc.

Oh TIL. We use clang-format pushing back into PRs in this repo so I could add that too: https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/format-code.yml

**Comment by jpnurmi** [comment]
:+1: for clang-format

P.S. Is melos considered the replacement of flutter_plugin_tools even though it uses flutter_plugin_tools for formatting?

**Comment by bruno-garcia** [comment]
> P.S. Is melos considered the replacement of flutter_plugin_tools even though it uses flutter_plugin_tools for formatting?

I see. I didn't know it used it `flutter_plugin_tools`.

**Pull request closed without merging**
