### PR TITLE
[connectivity_plus_linux] Bump nm to 0.5.0

### PR DESCRIPTION
**Pull request by prateekmedia**
## Description

`dbus` plugin 0.7.0 is out so `gsettings` is conflicting with `connectivity_plus` as they both are dependent on `dbus`. So I Bumped `nm` to 0.5.0.

Also I bumped `connectivity_plus_linux` to 1.3.0 and updated the CHANGELOG.

## Related Issues

N.A.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by prateekmedia** [comment]
ping @jpnurmi @Elias8 @mhadaily

**Comment by vbuberen** [comment]
@prateekmedia 
1. This is not right to ping people if they are not rushing to solve your problem right away, since this is not a commercial project and not their job to wait for every single PR and check it right away.

2.  Your PR fails on CI checks. Please fix them first.

**Comment by vbuberen** [comment]
> The change looks good.

I think that this change would also need a bump for `connectivity_plus` plugin itself with bumping min dependency on `connectivity_plus_linux`.

**Comment by prateekmedia** [comment]
I have bumped `connectivity_plus` to 2.2.1 and also updated it's CHANGELOG.

**Comment by vbuberen** [comment]
Thanks for your contribution

**Review by vbuberen — APPROVED** [review]

**Pull request merged**
