### PR TITLE
[network_info_plus] ios: handle deprecation of `CNCopyCurrentNetworkInfo`

### PR DESCRIPTION
**Pull request by alexbatalov**
## Description

This PR migrates network info to modern `NEHotspotNetwork` APIs while keeping backward compatibility with older iOS versions. The code looks a little bit overkill for a couple of simple conditions though.

## Related Issues

#240

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by diegotori** [comment]
LGTM. It's definitely separating out the deprecated and current implementations cleanly.

**Comment by diegotori** [comment]
@mhadaily Can we please get a review and approval? Thanks in advance.

**Comment by mhadaily** [comment]
I'll do @diegotori just give me a bit of time

**Comment by mhadaily** [comment]
can you please merge with `main` 

Update the changelog file and pump a minor version, please? 

thanks

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
