### PR TITLE
fix(device_info_plus): unexpected , separator

### PR DESCRIPTION
**Pull request by 23doors**
## Description

Fix for Package.swift which causes compilation errors on apps where swift package manager is enabled.

## Checklist

- [X] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [X] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [X] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by 23doors** [comment]
similar issue in package_info_plus, added it as well

**Comment by miquelbeltran** [comment]
Hey! Thanks for this fix. Can you check if the other projects also comply with this? Either we do one single PR with a fix for all plugins, or we do separated PRs per project.

**Comment by 23doors** [comment]
@miquelbeltran to be honest, I'm not exactly sure if they comply fully and as I got 0 experience with swift package manager ;) I just had compilation errors with these 2 projects and figured it was just a simple syntax error in swift files. I checked all other Package.swift files in this project and got no complaints from the IDE like from these 2. So I guess, they should be fine? 

In the end I had to turn off swift package manager for my app for now, as I had issues with csqlite package that I couldn't solve just yet. But after these 2 fixes in this PR, at least it compiled succesfully ;)

**Comment by vbuberen** [comment]
Thanks a lot for your contribution. I will give it a test a bit later today and merge it.

**Comment by vbuberen** [comment]
Once again thanks for catching the issue and opening a PR. In order to generate correct changelogs I created separate PRs for packages with your changes: 
#3405
#3406 

Thus, closing this PR in favor of those smaller ones.

**Pull request closed without merging**
