### PR TITLE
[all] Fix formatting issues

### PR DESCRIPTION
**Pull request by miquelbeltran**
## Description

Runs `melos run format` and fixes multiple formatting issues

The CI has been adapted to accept the formatting output of `melos run format` by removing the `--style=Google` parameter in the clang-format call for Objective-C classes.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Objective-C formatting seems to give different results when running `melos format` on my machine and on CI, I will take a look at that

**Comment by miquelbeltran** [comment]
The problem with Objective-C, is that `melos run format` formats it in the default `clang-format` style, but CI requires the "Google" style. This will cause a problem in the future when we run `melos run format`.

To simplify thing, I am changing CI to format using the default formatting like the `melos run format`.

**Review by vbuberen — COMMENTED** [review]
As I understand the main change is in `all_plugins.yaml` and other things are just reformatting.

Suggest to also modify `editorconfig` file to include rules to Objective-C.

**Comment by miquelbeltran** [comment]
Correct, the `all_plugins.yaml` is the only relevant change.

I will look at adding a configuration for `.m` on `editorconfig`. Would it be necessary for this PR?

**Comment by vbuberen** [comment]
> Would it be necessary for this PR?

I would do it, considering that it is directly related as well and pretty trivial change.

**Pull request merged**
