### PR TITLE
fix(share_plus): fallback for shareXFiles() to use download on web

### LINKED ISSUE #1643: [Bug]: share_plus Share.shareXFiles() is not working on web
### Platform

Flutter tools web browser running on macos

### Plugin

share_plus

### Version

latest from the main

### Flutter SDK

3.7.8

### Steps to reproduce

1. Checkout latetst sources from main
2. Open project in Android Studio
3. Select Chrome (web) as target and launch share_plus/example app
4. Click on the "Share XFile from Assets" button
5. The following exception is thrown but the plugin readme says "it falls back to downloading the shared files" when Web Share API is not available.

### Code Sample

```dart
The `share_plus/example` app from https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
```

### Logs

```shell
Debug service listening on ws://127.0.0.1:50601/BFGEsW3RKXM=/ws
TypeError: this.share is not a function
dart-sdk/lib/html/dart2js/html_dart2js.dart 22933:49                              share]
packages/share_plus/src/share_plus_web.dart 105:22                                shareXFiles
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 558:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1587:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37367:58                              <fn>
```

### Flutter Doctor

```shell
.../flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.6.1 21G217 darwin-arm64, locale en-CA)
    • Flutter version 3.7.8 on channel stable at .../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (5 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

### PR DESCRIPTION
**Pull request by ekuleshov**
## Description

Adds fallback to use download files on web when `Navigator.share()` failed

## Related Issues

- *Fix #1643*

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Thanks for the PR! I will check it in the following days. Meanwhile, there are formatting errors in `packages/share_plus/share_plus/example/lib/main.dart` and `packages/share_plus/share_plus/lib/src/share_plus_web.dart`.

**Comment by miquelbeltran** [comment]
Taking a look at it now. So I think it's a good start, but I think that if we want to follow the idea that it should always fallback to download, then on _any_ point of failure should fall back to downloading and not just the `NotAllowedError`. That would mean that, for example, the call to `throw Exception('Navigator.canShare() is unavailable');` on line 207 should also be replaced by a call to `_download()`, also on 211, etc.

**Comment by ekuleshov** [comment]
> Taking a look at it now. So I think it's a good start, but I think that if we want to follow the idea that it should always fallback to download, then on _any_ point of failure should fall back to downloading and not just the `NotAllowedError`. That would mean that, for example, the call to `throw Exception('Navigator.canShare() is unavailable');` on line 207 should also be replaced by a call to `_download()`, also on 211, etc.

Makes sense. I'll update.

Also, the API docs says that `shareXFiles()` method "May throw `PlatformException` or `FormatException` from `MethodChannel`", but the web implementation throws plain `Exception`. Should I change it to use the `PlatformException` instead?

I also wonder if there should be a flag on the `shareXFiles()` method to enable/disable this fallback?
Perhaps that could be done as part of https://github.com/fluttercommunity/plus_plugins/issues/3307#issuecomment-2513723902

**Comment by miquelbeltran** [comment]
> Also, the API docs says that `shareXFiles()` method "May throw `PlatformException` or `FormatException` from `MethodChannel`", but the web implementation throws plain `Exception`. Should I change it to use the `PlatformException` instead?

I think `Exception` is fine, instead the documentation should be updated once this feature is ready.

> I also wonder if there should be a flag on the `shareXFiles()` method to enable/disable this fallback? Perhaps that could be done as part of [#3307 (comment)](https://github.com/fluttercommunity/plus_plugins/issues/3307#issuecomment-2513723902)

I was thinking that as well. Maybe is a very dirty hack, but even a static variable with a flag to enable/disable the download fallback could be an option. And then refactor properly in #3307

**Comment by ekuleshov** [comment]
> > I also wonder if there should be a flag on the `shareXFiles()` method to enable/disable this fallback? Perhaps that could be done as part of [#3307 (comment)](https://github.com/fluttercommunity/plus_plugins/issues/3307#issuecomment-2513723902)
> 
> I was thinking that as well. Maybe is a very dirty hack, but even a static variable with a flag to enable/disable the download fallback could be an option. And then refactor properly in #3307

Updated.

On a side note. The [XFile.saveTo(path)](https://github.com/flutter/packages/blob/8238e1c5ada8c6a99f7fb6087484b52face33721/packages/cross_file/lib/src/types/html.dart#L205C30-L221) on the web also makes a file download with the `HTMLAnchorElement`. The "path" parameter is ignored and `XFile.name` is used for downloaded files, which won't allow for `fileNameOverrides`.

**Comment by miquelbeltran** [comment]
I've made some changes to the PR:

- Moved the `downloadFallbackEnabled` to the `Share` class so it is accessible
- Updated the README
- Added trailing comas to the methods
- Wrapped the example "share from assets" in a try/catch
- Added the `downloadFallbackEnabled` to the example so it can be tested

**Comment by ekuleshov** [comment]
Looks good.

PS: those trailing comas are going away when dart_style is bumped to 3.0.0. Hopefully you could increase line length from 80 to 120 at that time...

**Comment by miquelbeltran** [comment]
I'll go ahead and merge, if there are any other necessary changes they can go in a new PR

> PS: those trailing comas are going away when dart_style is bumped to 3.0.0. Hopefully you could increase line length from 80 to 120 at that time...

Interesting.. now taking a look at https://github.com/dart-lang/dart_style/issues/1253

**Pull request merged**
