### PR TITLE
[package_info_plus] fix app name on iOS and macOS

### PR DESCRIPTION
**Pull request by alexbatalov**
## Description

This PR adds fallback to `CFBundleName` if `CFBundleDisplayName` does not exist. This approach is suggested by Apple in [QA1544](https://developer.apple.com/library/archive/qa/qa1544).

## Related Issues

#432 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mhadaily** [comment]
can you merge with `main` and push one more time. thanks

**Comment by alexbatalov** [comment]
git says it's already up to date with main

**Comment by mhadaily** [comment]
Perfect, can you please pump minor version and add this to changelog ? thanks

**Review by mhadaily — APPROVED** [review]
LGTM

**Review by mhadaily — APPROVED** [review]
LGTM

**Pull request merged**
