### PR TITLE
Fixes crashes in connectivity_plus and battery_plus

### PR DESCRIPTION
**Pull request by jdebou**
## Description

Fixes a crash caused by a ressource that was not kept alive.

## Related Issues

#404 #734 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by jdebou** [comment]
I tested some more with that patch and it is still flaky. I'm going to keep investigating.

**Comment by jdebou** [comment]
I have found that `UnregisterPowerSettingNotification` was called with a local object. I believe this to cause an error down the line when calling `GetLastError`, which somehow tries to use a reference to the now deleted `notifier`.

**Comment by jdebou** [comment]
Turns out I was building without the patch, hence the patch not working.

Can someone review this one? Thanks

**Comment by miquelbeltran** [comment]
thank you! I will release the fix asap

**Pull request merged**
