### PR TITLE
update and remove win32

### PR DESCRIPTION
**Pull request by nimr77**
## Description

There was an issue while updating to flutter 3.10, one of the plugins WIN32 uses an old plugin chiew 1.0.0, so had to remove it and it didn't break anything so far

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*

*e.g.*
- *Fix #123*
- *Related #456*

## Checklist

- [ ] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by vbuberen** [comment]
> There was an issue while updating to flutter 3.10, one of the plugins WIN32 uses an old plugin chiew 1.0.0, so had to remove it and it didn't break anything so far

There are no issues with building projects with Flutter 3.10 and current version of `share_plus`. Also, `win32` doesn't use any `chiew` dependencies that you mentioned. So you need to deal with your build config in the project and not touch plugins that have nothing to do with your setup.

**Comment by nimr77** [comment]
I was getting this error,
```
Because no versions of share_plus match >7.0.0 <8.0.0 and share_plus 7.0.0 depends on win32 ^4.0.0, share_plus ^7.0.0 requires win32 ^4.0.0.
Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows requires win32 ^2.0.0 or ^3.0.0.
Thus, share_plus ^7.0.0 is incompatible with wakelock_windows.
And because chewie >=1.3.5 depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, share_plus ^7.0.0 is incompatible with chewie >=1.3.5.
So, because app depends on both chewie ^1.4.0 and share_plus ^7.0.0, version solving failed.
exit code 1
```

**Comment by timsneath** [comment]
The issue is that wakelock_windows (a dependency of chewie) relies on an old version of win32. I've sent the author a PR to fix this:
https://github.com/creativecreatorormaybenot/wakelock/pull/203

**Comment by nohli** [comment]
You could try this in your `pubspec.yaml` to workaround the issue with `pub get`:

```
dependency_overrides:
  win32: ^4.0.0
```

**Pull request closed without merging**
