### PR TITLE
refactor(network_info_plus): Rewrite Windows implementation in Dart

### PR DESCRIPTION
**Pull request by timsneath**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*

*e.g.*
- *Fix #123*
- *Related #456*

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by vbuberen** [comment]
Looks like we are having issues with web integration tests here.

**Comment by timsneath** [comment]
@vbuberen Yeah, I see that. I can't figure out what's different between this and other Win32-based packages that are already implemented.

**Comment by vbuberen** [comment]
It seems that we needed to change exports a bit.
As you might see from my commits I changed export of windows class to include condition:

```
export 'src/network_info_plus_windows.dart'
  if (dart.library.html) 'src/network_info_plus_web.dart';
```
And now web compiles again.

**Comment by timsneath** [comment]
I should note that the implementation here is relatively naive. The APIs called assume a wireless network adapter, and may not show valid results on a wired machine. 

My goal for the initial Dart implementation was to offer a mapping to the existing C implementation that exactly mirrors the API calls made there, so that this should be a true slot-in replacement. 

When that's complete and @halildurmus' work on projecting the Windows Runtime APIs is published, we should update this implementation with more modern APIs.

**Comment by vbuberen** [comment]
Thanks a lot for additional information and this refactoring. I will merge it and release today.

**Review by vbuberen — APPROVED** [review]

**Pull request merged**
