### PR TITLE
refactor(network_info_plus)!: two-package federated architecture

### PR DESCRIPTION
**Pull request by nohli**
## Description

Refactor network_info_plus from the federated architecture to a platform interface and a package with all platform implementations.

## Related Issues

https://github.com/fluttercommunity/plus_plugins/issues/1226

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by nohli** [comment]
Only the windows build is broken.
Could you please take a look @miquelbeltran, you fixed the windows build in a few commits [here](https://github.com/fluttercommunity/plus_plugins/pull/1227) 🙂

**Comment by miquelbeltran** [comment]
Sure! Will do in the upcoming days

**Comment by miquelbeltran** [comment]
Alright windows build is fixed, but actually I wasn't able to retrieve a single value using the example, so I am not even sure this plugin works -at all- on windows :)

**Comment by nohli** [comment]
> Alright windows build is fixed, but actually I wasn't able to retrieve a single value using the example, so I am not even sure this plugin works -at all- on windows :)

Thanks a lot!!

Could you please try if it works on `main`? If not, this PR at least wouldn't worsen anything.

During testing all plugins in the simulators, I often found values to be null. Thought, it's maybe a simulator thing. Or for example sensors on web.

**Comment by miquelbeltran** [comment]
> Why the `if (!Platform.isWindows) {` in example? Does it throw?

Yeah, it crashes, so it is impossible to run the example. These methods are not available on Windows as they are not implemented.

I will check with main as well for the other methods, but I suspect they don't work either. Maybe because I am on an ethernet connection? 😂

**Comment by miquelbeltran** [comment]
Same thing on `main`

**Review by miquelbeltran — APPROVED** [review]

**Review by vbuberen — APPROVED** [review]

**Pull request merged**
