### PR TITLE
sometimes deviceMemory is null on web

### PR DESCRIPTION
**Pull request by KirillArtemenko**
more info here:
https://github.com/fluttercommunity/plus_plugins/issues/255

### CODE REVIEW

**Comment by KirillArtemenko** [comment]
I created another PR, it is better coz more backward compatible and no need any changes for ios/android of plugin developers.

https://github.com/fluttercommunity/plus_plugins/pull/257

**Comment by miquelbeltran** [comment]
Thanks for the fix @KirillArtemenko !

I am thinking that maybe it makes more sense to make all the properties in `WebBrowserInfo` nullable instead, because we really don't have any warranties that the "navigator" will provide all or any of those fields.

But I am happy to just merge this as a temporal solution. Could you also bump the build number in the pubspec.yaml and add an entry on CHANGELOG as explained in the contributing document?

**Comment by KirillArtemenko** [comment]
> Thanks for the fix @KirillArtemenko !
> 
> I am thinking that maybe it makes more sense to make all the properties in `WebBrowserInfo` nullable instead, because we really don't have any warranties that the "navigator" will provide all or any of those fields.

I thought about it, but this change will entail a change to the main interface. And other developers will need to update their code due to the fact that some of the fields will become nullable. So I decided another this solution.

**Comment by KirillArtemenko** [comment]
> But I am happy to just merge this as a temporal solution. Could you also bump the build number in the pubspec.yaml and add an entry on CHANGELOG as explained in the contributing document?

Please make the PR and changes yourself. Sorry for the mess. I'm creating this PR from the internet, and right now I can't create it properly. Next time I'll create a normal PR from my local git. Take my word for it )

**Pull request closed without merging**
