### PR TITLE
fix(share_plus): Present Share Sheet on the top ViewController 

### PR DESCRIPTION
**Pull request by searchy2**
## Description

Update iOS share target to present on the top ViewController. This fixes "Unable to present" errors when the app is already presenting such as in an add to app scenario.

## Related Issues

https://github.com/fluttercommunity/plus_plugins/issues/251

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
No tests need to be updated. 
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
No doc changes needed.
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
`warning - The path F:\Development\FlutterPlusPlugins\packages\share_plus is not posix - example\pubspec.yaml:9:11 - path_not_posix`
- [X] I read and followed the [Flutter Style Guide].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Thanks @searchy2 ! Can you update also the pubspec.yaml and bump the version number to `2.1.3`?

**Comment by searchy2** [comment]
Bumped!

**Comment by miquelbeltran** [comment]
I tested this and seems to work, however CI is complaining with the following error:

```
These files are not formatted correctly:


-----------------------------------------------------------------
packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
-----------------------------------------------------------------

diff --git a/packages/share_plus/ios/Classes/FLTSharePlusPlugin.m b/packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
index accd0e7..1caf92d 100644
--- a/packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
+++ b/packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
@@ -154 +154 @@ static UIViewController *TopViewControllerForViewController(UIViewController *vi
-        TopViewControllerForViewController(RootViewController());
+          TopViewControllerForViewController(RootViewController());
@@ -183 +183 @@ static UIViewController *TopViewControllerForViewController(UIViewController *vi
-        TopViewControllerForViewController(RootViewController());
+          TopViewControllerForViewController(RootViewController());

-----------------------------------------------------------------
```

Could you solve this formatting issue? then I will merge and release.

**Comment by searchy2** [comment]
I'll probably need your help with the formatting. 
Trying to run the format command `melos run format` outputs this error;
```
F:\Development\FlutterPlusPlugins>flutter pub global run flutter_plugin_tools fo
rmat
Unhandled exception:
Invalid argument(s): join(null, "gcloud-service-key.json"): part 0 was null, but
 part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1102:5)
#1      Context.join (package:path/src/context.dart:242:5)
#2      join (package:path/path.dart:265:13)
#3      new FirebaseTestLabCommand (package:flutter_plugin_tools/src/firebase_te
st_lab_command.dart:33:13)
#4      main (package:flutter_plugin_tools/src/main.dart:54:18)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isola
te_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:184:12)
pub finished with exit code 255
```

**Comment by searchy2** [comment]
@miquelbeltran Can you help me fix the formatting?

**Comment by mhadaily** [comment]
can you also please merge with `main`, we have fixed a few things for CD/CI

**Comment by searchy2** [comment]
Done!

**Comment by mhadaily** [comment]
Perfect, now it seems we have a formatting issue, could you run `melos run format` on your machine and commit the changes too? @searchy2  THANK YOU

**Comment by searchy2** [comment]
That didn't work and threw an exception. I'll need you to run it for me.

**Comment by mhadaily** [comment]
What's the exception? 

if you want me to run it for you, you need to give me access to https://github.com/searchy2/plus_plugins/tree/share_ios_present_fix

**Comment by searchy2** [comment]
I'm running into the same issue as before:
```
F:\Development\FlutterPlusPlugins>flutter pub global run flutter_plugin_tools fo
rmat
Unhandled exception:
Invalid argument(s): join(null, "gcloud-service-key.json"): part 0 was null, but
 part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1102:5)
#1      Context.join (package:path/src/context.dart:242:5)
#2      join (package:path/path.dart:265:13)
#3      new FirebaseTestLabCommand (package:flutter_plugin_tools/src/firebase_te
st_lab_command.dart:33:13)
#4      main (package:flutter_plugin_tools/src/main.dart:54:18)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isola
te_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:184:12)
pub finished with exit code 255
```

I've invited you to the repo, thank you for your help here!

**Comment by miquelbeltran** [comment]
@searchy2 can you enable “Allow edits by maintainers”? I just checked out your PR and there were still unmerged changes from `main`.

**Comment by searchy2** [comment]
It's checked, just updated from main again.

**Comment by miquelbeltran** [comment]
Can you run `melos run format`?

**Comment by miquelbeltran** [comment]
going to unblock this, may need to create a new PR

**Comment by miquelbeltran** [comment]
continuing in #307

**Pull request closed without merging**
