### PR TITLE
feat: get scheduled alarms functionality added.

### PR DESCRIPTION
**Pull request by Chinmay-KB**
## Description

The plugin now stores all the upcoming alarms, be it one shot or periodic and returns a json string containing info about all the
scheduled alarms.  Oneshot alarms are removed from this list when the alarm goes off. Peroidic alarms are removed only when it is explicitly cancelled.

## Related Issues

#342 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mhadaily** [comment]
Formating has some issues, can you please ensure you are running `melos run format` and make sure you are installing all necessary dependencies on your machine.

**Comment by Chinmay-KB** [comment]
I was having some issues with installing melos last time I tried. Let me try this weekend and let you know.

**Comment by miquelbeltran** [comment]
Can you add a usage example for this new method? in the example project if possible, so I can run it and verify that it works

**Comment by Chinmay-KB** [comment]
@miquelbeltran sure

**Comment by Chinmay-KB** [comment]
@miquelbeltran I have added a small example in the example project.
This example project adds oneshot alarms at a random duration between 1000ms and 1000 + 4096ms. So hitting the same button multiple times registers multiple alarms. After setting multiple alarms, if we press fetch alarms button, a json string is shown, containing details of all the alarms scheduled. As andwhen the alarms fire, one can see the details of that alarm being removed from the json.

**Comment by miquelbeltran** [comment]
thanks @Chinmay-KB I'll try to take a look soon

**Comment by miquelbeltran** [comment]
Also @Chinmay-KB the PR is marked as Draft. Is there anything else you want to work with or is it fine to go?

**Review by miquelbeltran — APPROVED** [review]

**Comment by Chinmay-KB** [comment]
> Also @Chinmay-KB the PR is marked as Draft. Is there anything else you want to work with or is it fine to go?

It is all from my end. It's my first pr to this plugin so I had it as a draft pr 😅

**Comment by miquelbeltran** [comment]
Cool, merged and published under 1.1.0

**Pull request merged**
