### PR TITLE
[device_info_plus] feat: more info for Windows (re-land #814)

### LINKED ISSUE #1023: [Question]: Why did you removed `productName` from `WindowsDeviceInfo` ?
### What is your question?

You removed almost all `WindowsDeviceInfo` .. why did you do this ?

### PR DESCRIPTION
**Pull request by alexmercerind**
## Description

This pull request re-introduces the `device_info_plus` changes in #814.
The cited changes were reverted due to not incrementing a major version. See: #1000 & #1009.

**This time (carefully), major versions of following packages have been updated:**

- `device_info_plus` : [5.0.0](https://github.com/harmonoid/plus_plugins/blob/2e1fa2628c42caf7d9bb5e46aadbd584b6d99909/packages/device_info_plus/device_info_plus/pubspec.yaml) from [4.1.3](https://pub.dev/packages/device_info_plus).
- `device_info_plus_platform_interface` : [4.0.0](https://github.com/harmonoid/plus_plugins/blob/2e1fa2628c42caf7d9bb5e46aadbd584b6d99909/packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml) from [3.0.0](https://pub.dev/packages/device_info_plus_platform_interface).
- `device_info_plus_windows` : [5.0.0](https://github.com/harmonoid/plus_plugins/blob/2e1fa2628c42caf7d9bb5e46aadbd584b6d99909/packages/device_info_plus/device_info_plus_windows/pubspec.yaml) from [4.1.0](https://pub.dev/packages/device_info_plus_windows).

Since, changes are only introduced in these three packages, other platform-specific packages have no version increment.

<hr>

**Original pull-request description:**

> Now `device_info_plus` fetches a lot more information on Windows compared to before.
This has many use-cases like identifying Windows version, getting username, install date, build number or product ID (for software license handling) etc.
>
> ### Reference Images
> [sensitive data is hidden]
>
> **Windows 10**
> 
> device_info_plus_10
> 
> **Windows 11**
> 
> device_info_plus_11
> 
> ```dart
> {
>   'computerName': computerName,
>   'numberOfCores': numberOfCores,
>   'systemMemoryInMegabytes': systemMemoryInMegabytes,
>   'userName': userName,
>   'majorVersion': majorVersion,
>   'minorVersion': minorVersion,
>   'buildNumber': buildNumber,
>   'platformId': platformId,
>   'csdVersion': csdVersion,
>   'servicePackMajor': servicePackMajor,
>   'servicePackMinor': servicePackMinor,
>   'suitMask': suitMask,
>   'productType': productType,
>   'reserved': reserved,
>   'buildLab': buildLab,
>   'buildLabEx': buildLabEx,
>   'digitalProductId': digitalProductId,
>   'displayVersion': displayVersion,
>   'editionId': editionId,
>   'installDate': installDate,
>   'productId': productId,
>   'productName': productName,
>   'registeredOwner': registeredOwner,
>   'releaseId': releaseId,
>   'deviceId': deviceId,
> }
> ```

## Related Issues

Closes #1023

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by alexmercerind** [comment]
iOS seems to be having some issue on CI. I can't seem to read logs either, took way too much time. Maybe re-run actions?

**Comment by miquelbeltran** [comment]
Thanks for the submission! Could you introduce a Windows integration_test that checks some of the new values? something like this: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart#L127

**Comment by alexmercerind** [comment]
Hi @miquelbeltran!

All the checks for newly added `WindowsInfo` values have passed here as-well.

https://github.com/fluttercommunity/plus_plugins/blob/d1f05bde0d1e7c90ff7b2a93ddb1a44bbee15e44/packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart#L140-L232

**Comment by vbuberen** [comment]
The PR looks great to me. Thanks a lot for such contribution!

**Review by miquelbeltran — APPROVED** [review]

**Pull request merged**
