### PR TITLE
fix(connectivity_plus): update and fixe bugs for connectivity_plus

### PR DESCRIPTION
**Pull request by mhadaily**
## Description

I tried to update our connectivity plugins to match the latest changes in Android and iOS and fix some bugs for the web.

## Related Issues

This PR will address 

https://github.com/fluttercommunity/plus_plugins/issues/62
https://github.com/fluttercommunity/plus_plugins/issues/260
https://github.com/fluttercommunity/plus_plugins/issues/198
https://github.com/fluttercommunity/plus_plugins/issues/98

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mhadaily** [comment]
I don't see any formatting issue 
✅ All files are formatted correctly.

not sure why it's failing!

**Comment by ueman** [comment]
> I don't see any formatting issue 
> ✅ All files are formatted correctly.
> 
> probably we should merge this PR first https://github.com/fluttercommunity/plus_plugins/pull/272

flutter format had a small change in how it formats source code. It seems like the failure is exactly that case. 

To reproduce it you can try running flutter format with 2.0.0 vs 2.2.0

**Comment by mhadaily** [comment]
> > I don't see any formatting issue
> > ✅ All files are formatted correctly.
> > probably we should merge this PR first #272
> 
> flutter format had a small change in how it formats source code. It seems like the failure is exactly that case.
> 
> To reproduce it you can try running flutter format with 2.0.0 vs 2.2.0

Thanks for the heads-up,

**Review by miquelbeltran — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
