### PR TITLE
[connectivity_plus] Remove unused IPHelper file

### PR DESCRIPTION
**Pull request by ChristianEdwardPadilla**
## Description

IPHelper.h is being used in the (now deprecated) [flutter/plugins/connectivity](https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity_macos) repo, but not in this plus_plugins repo. We can re-add it when needed.

## Related Issues

None.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by ChristianEdwardPadilla** [comment]
Not sure the macos-latest test is cancelling for a good reason or not. Anyone know?

**Comment by mhadaily** [comment]
I just updated main branch can you please  update with `main`

**Comment by mhadaily** [comment]
Thanks looks good one more favor, 

Can you please add a changelog and pump version of the package? 

thank you

**Comment by mhadaily** [comment]
> Not sure the macos-latest test is cancelling for a good reason or not. Anyone know?

passing now

**Review by nohli — APPROVED** [review]

**Review by miquelbeltran — APPROVED** [review]
LGTM. As the file functionality was moved into network_info_plus there's no need to have it here. Probably a new release is not necessary either.

**Pull request merged**
