### PR TITLE
fix(device_info_plus): suppress Android build deprecation warnings

### PR DESCRIPTION
**Pull request by nohli**
## Description

The plugin is updated to use Android v2 embedding, while keeping the registerWith() method for keeping backwards compatibility.
Since it's deprecated, there are warnings on every Android build.
This PR suppresses the warnings.

## Related Issues

```
/opt/homebrew/Caskroom/flutter/2.5.0/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus-2.1.0/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java:11: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
/opt/homebrew/Caskroom/flutter/2.5.0/flutter/.pub-cache/hosted/pub.dartlang.org/device_info_plus-2.1.0/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java:19: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(Registrar registrar) {
                                  ^
2 warnings

```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by mhadaily — APPROVED** [review]
LGTM, 

@nohli I wish you can send similar PR for other packages too. that would be awesome.

**Comment by nohli** [comment]
> LGTM,
> 
> @nohli I wish you can send similar PR for other packages too. that would be awesome.

Ok, will do! 🙂 

Thanks for adding hacktoberfest-accepted!

**Comment by nohli** [comment]
@mhadaily I opened PRs for the six other packages that use the deprecated method without suppressing warnings.

Would be cool if you also added the hacktoberfest-accepted tag.

I also updated the version and changelog to save you time, hope that's ok.

**Comment by juliansteenbakker** [comment]
@nohli wouldn't it be better to remove the whole registerWith function, since new Flutter plugins also don't ship with this function anymore. See https://flutter.dev/docs/release/breaking-changes/android-v1-embedding-create-deprecation for more info.

**Comment by nohli** [comment]
Did you see my comment and the link in https://github.com/fluttercommunity/plus_plugins/pull/442#issuecomment-932521729?

Flutter advises to keep this method. Idk how old the linked docs are.

If new packages don't use the method any more, in my opinion it's okay because it's no breaking change for old users (that don't exist).
Removing it from a package that has been around for some time would be a breaking change, right?

**Comment by juliansteenbakker** [comment]
> @juliansteenbakker Did you see my comment and the link in [#442 (comment)](https://github.com/fluttercommunity/plus_plugins/pull/442#issuecomment-932521729)?
> 
> Flutter advises to keep this method. Idk how old the linked docs are.
> 
> If new packages don't use the method any more, in my opinion it's okay because it's no breaking change for old users (that don't exist). Removing it from a package that has been around for some time would be a breaking change, right?

I think you are right. I checked all official Google plugins and they all contain registerWith function. I'll change my PR accordingly (#442)

Just one more question, should the version of this package not be 2.2.1 instead of 2.3.0? It doesn't seem like that big of a change.

**Comment by mhadaily** [comment]
@nohli this is great, but can we focus on one PR for all of the package related to this, I commented on your PRs. 

thanks

**Comment by mhadaily** [comment]
@nohli let me know when you can close all other PR and merge them all into one PR

thanks

**Comment by nohli** [comment]
@mhadaily have we decided on how to handle the deprecations?
Before opening another PR, I would like to clearly know the requirements.

The registerWith method takes Registrar which is deprecated.
Options:
- Removing the method altogether and stop supporting Android v1 embedding
-> breaking change with major version upgrade?
- Keeping the method and suppressing the deprecation warning

And do you want me to also close this PR and open a new one?

**Comment by mhadaily** [comment]
Let us remove Android v1 embedding support and release a new major version. 
Let us be fully compatible with new APIs as most Flutter developers also use v2 embedding. 

If there are still apps that use v1, they can use an older version.  I don't see any big concern about removing V1 support as long as we release a major version. 

I'd recommend you also take a look at FlutterFire to see if they follow. 

thoughts?

**Comment by nohli** [comment]
Okay, will do 😊

Your last sentence means to also open a similar PR over there?

**Comment by mhadaily** [comment]
If you are comfortable with this PR, please continue on this one and please close all others. I just like to see one PR for this issue to be honest. I'll leave it to you whether you open a new one or continue on this one, both works for me.

**Review by mhadaily — CHANGES_REQUESTED** [review]
as we discussed

**Comment by nohli** [comment]
Closing because of https://github.com/fluttercommunity/plus_plugins/pull/495

**Pull request closed without merging**
