### PR TITLE
[battery_plus] null-safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
See #50

### CODE REVIEW

**Comment by miquelbeltran** [comment]
blocked by this: ```The current Dart SDK version is 2.12.0-259.12.beta.

Because no versions of dbus match >0.2.0 <0.3.0 and dbus 0.2.0 depends on xml ^5.0.0, dbus ^0.2.0 requires xml ^5.0.0.
Because xml 5.0.0 requires SDK version >=2.12.0-259.14.beta <3.0.0 and no versions of xml match >5.0.0 <6.0.0, xml ^5.0.0 is forbidden.
Thus, dbus ^0.2.0 is forbidden.
So, because battery_plus_linux depends on dbus ^0.2.0, version solving failed.
pub get failed (1; So, because battery_plus_linux depends on dbus ^0.2.0, version solving failed.```

**Comment by jpnurmi** [comment]
Is it because `xml` sdk contraint is `'>=2.12.0-259.14.beta <3.0.0'`?

https://github.com/renggli/dart-xml/blob/main/pubspec.yaml#L8

**Comment by jpnurmi** [comment]
It's not only `xml` but also its dependency `petitparser`: https://github.com/petitparser/dart-petitparser/pull/97

**Comment by jpnurmi** [comment]
Aaaand next:
```
Running "flutter pub get" in example...                         
Because every version of battery_plus from path depends on battery_plus_linux from path which depends on dbus ^0.2.0, every version of battery_plus from path requires dbus ^0.2.0.
And because dbus >=0.2.0 depends on args ^2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, battery_plus from path is incompatible with flutter_driver from sdk.
So, because battery_plus_example depends on both flutter_driver any from sdk and battery_plus from path, version solving failed.
pub get failed (1; So, because battery_plus_example depends on both flutter_driver any from sdk and battery_plus from path, version solving failed.)
```

**Review by jpnurmi — COMMENTED** [review]
To get past the `args` conflict, you can add to `battery_plus/example/pubspec.yaml`:

```
dependency_overrides:
  args: ^2.0.0
```

https://github.com/fluttercommunity/plus_plugins/issues/50#issuecomment-782284716

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:

**Comment by miquelbeltran** [comment]
Thank you!

**Pull request merged**
