### PR TITLE
Port connectivity_plus_linux to nm.dart

### PR DESCRIPTION
**Pull request by jpnurmi**
Use the ready-made [nm](https://pub.dev/packages/nm) package instead of accessing the Network Manager API over D-Bus.

### CODE REVIEW

**Review by mhadaily — APPROVED** [review]
LGTM. I am not sure if we should care about code coverage or not.

**Comment by jpnurmi** [comment]
The tests are covering just as much of the remaining code in the Linux plugin. The total code coverage percent is less because plenty of previously tested code was removed. We get this functionality now "for free" from the official "nm" Dart package.

**Comment by mhadaily** [comment]
Then feel free to merge and release a new version

**Review by mhadaily — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
Thanks! I have a new feature (`ConnectivityResult.ethernet`) in the works. Then we'll have an actual reason to bump all `connectivity_plus` versions and update changelogs. :smile:

**Pull request merged**
