### PR TITLE
Connectivity_plus detect no-network on Android M and above

### PR DESCRIPTION
**Pull request by innim98**
## Description

connectivity_plus plugin uses ConnectivityManager.NetworkCallback() when the Android OS version is VERSION_CODES.M or above.
Once the network is changed, it sends the latest network state to Flutter by using ConnectivityManager.getActiveNetwork()
(Ref: connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java)
Sometimes getActiveNetwork() returns the network interface (not null) which is just disconnected for network disconnection.
This causes that the network state is shown as connected when it's disconnected.

* I just created a simple patch since the issue #290 is not fixed quickly. If you have a better fix already prepared, please ignore this PR.

## Related Issues

https://github.com/fluttercommunity/plus_plugins/issues/290

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by mhadaily — APPROVED** [review]
LGTM, @miquelbeltran any objection?

**Comment by mhadaily** [comment]
@innim98 can you please increase the version in the package and add a changelog so we can release it after merging.

**Comment by innim98** [comment]
Updated the version and change log. Thank you.

**Comment by miquelbeltran** [comment]
@mhadaily yes, make sense to me!

**Comment by innim98** [comment]
@mhadaily could you merge if it's okay?

**Pull request merged**
