### PR TITLE
add default values for all nullable

### PR DESCRIPTION
**Pull request by KirillArtemenko**
Add default values for all nullable properties, without it we can get NPE at WebBrowserInfo.fromMap() at the main device_info_platform_interface plugin
more info here:
https://github.com/fluttercommunity/plus_plugins/issues/255

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Oh I see now the new PR. If the previous one is no longer required, can you close it?

**Comment by KirillArtemenko** [comment]
Please look this (more correct) solution: #258

**Comment by mhadaily** [comment]
can you also please merge with `main`

**Comment by miquelbeltran** [comment]
I am going to continue on the other PR making all values nullable

**Comment by KirillArtemenko** [comment]
Thank you but still not available here https://pub.dev/packages/device_info_plus
Update please.

**Pull request closed without merging**
