### PR TITLE
Update android_alarm_manager_plus_test.dart

### PR DESCRIPTION
**Pull request by ok-open-sc**
## Description

Updated android_alarm_manager_plus_test.dart in ackages/android_alarm_manager_plus/example/integration_test/android_alarm_manager_plus_test.dart

## Related Issues

Previous android_alarm_manager_plus_test.dart was not working.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by nohli** [comment]
Hi @ok-open-sc, did you copy the test from the flutter create template?

**Comment by ok-open-sc** [comment]
> lutter create template

No

**Comment by ok-open-sc** [comment]
> Hi @ok-open-sc, did you copy the test from the flutter create template?

No

**Comment by miquelbeltran** [comment]
closed due to low quality submission

**Pull request closed without merging**
