### PR TITLE
build(share_plus)!: Target Java 17 on Android

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

Same as #2723 

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Review by miquelbeltran — APPROVED** [review]

**Comment by orkun1675** [comment]
Since this PR I'm getting the following error when trying to build for Android:

```
Execution failed for task ':share_plus:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (1.8).
```

Could you explain what kind of migration is neccesary?

**Comment by vbuberen** [comment]
> Could you explain what kind of migration is neccesary?

You need to change your `build.gradle` like it was changed in this PR to specify Java 17 to use during compilation of Kotlin code. From your error it looks like you have `1.8` specified in `kotlinOptions` section of your `build.gradle` file.

> Do we need to upgrade to Gradle 8.4 even though it's in [beta](https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin)?

You are confusing Android Gradle Plugin and Gradle itself. While Android Gradle Plugin 8.4 is indeed in beta, Gradle 8.4 itslef isn't in beta. We require Gradle wrapper version to be 8.4. Gradle wrapper is specified in files like this inside any project: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/share_plus/android/gradle/wrapper/gradle-wrapper.properties

**Comment by orkun1675** [comment]
Thanks Volodymyr.

I have updated to Java 17 and Gradle Wrapper 8.4. I have kept Gradle Plugin at 8.2.2 due to a [bug with 8.3](https://issuetracker.google.com/issues/327696048).

Unfortunately this only replaced ther error with:

```
Execution failed for task ':games_services:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (17).
```

I'm not sure why, since the game_services plugin does not specify a Java or Kotlin version? [link](games_services/android/build.gradle)

As a final result, based on this [Stackoverflow post](https://stackoverflow.com/a/77861041/3531663), I added `kotlin.jvm.target.validation.mode = IGNORE` to my `gradle.properties` file. This doesn't sound great. But did fix the build issue.

**Comment by vbuberen** [comment]
And what about Java compile options? Did you also change it to 17 like it is done in this PR? 
Both Java compile and Kotlin compile tasks should have the same Java target version.

These 2 lines are the ones responsible for Java version for Java compile: https://github.com/fluttercommunity/plus_plugins/pull/2730/files#diff-2607f8958e631dcb7f1ce17b341b8520cde253d7cde36a0bafc64d98676f4270R33

**Comment by vbuberen** [comment]
What is `game_services` plugin? 🤔 Not sure I understood that line

**Comment by orkun1675** [comment]
Yes, I did replaced the compile options with Java 17 as well. Here is the full `app/build.gradle` file: https://pastebin.com/ZQMH5NLf

And the settings.gradle file is: https://pastebin.com/WeXLHTab

Sorry for the broken link for the game_services plugin. I've updated it above.

**Pull request merged**
