### PR TITLE
fix(connectivity_plus): Add connectivity_plus_web export

### PR DESCRIPTION
**Pull request by nohli**
## Description

This PR adds a missing export.

## Related Issues

https://github.com/fluttercommunity/plus_plugins/pull/1227#discussion_r999845769

## Checklist

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miquelbeltran** [comment]
In my case, `connectivity_plus` works on web without needing this change. Maybe is there's something that has changed by adding the flutter sdk requirement for 2.11?

**Review by miquelbeltran — APPROVED** [review]
LGTM, although I didn't need this fix for me to work, I guess some users may need this depending on the SDK version they are running.

**Comment by nohli** [comment]
> In my case, `connectivity_plus` works on web without needing this change. Maybe is there's something that has changed by adding the flutter sdk requirement for 2.11?

[This issue](https://github.com/fluttercommunity/plus_plugins/pull/1227#discussion_r999647584) was before the sdk change 🤷🏽‍♂️

**Review by vbuberen — APPROVED** [review]
I hope that this fix will be the last one for this move to 2 package structure 😄

**Comment by nohli** [comment]
Well, the Android test is still failing 🙈

**Comment by miquelbeltran** [comment]
> Well, the Android test is still failing 🙈

no worry about this, it is because the API 21 integration test fails, but it works on more recent Android versions ;)

**Comment by nohli** [comment]
Can we fix the test?

Another pub.dev/GitHub release today? 🙂

**Pull request merged**
