### PR TITLE
[package_info_plus] Make PackageInfo testable with mock data

### PR DESCRIPTION
**Pull request by Boehrsi**
## Description

Added a similar method as already given in the shared_preference plugin (https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L196), to allow the easy usage of the package_info_plus plugin during tests. The method allows the setup of mock data and also enables the developer to change the data during tests.

## Related Issues

Fixes https://github.com/fluttercommunity/plus_plugins/issues/145

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by Boehrsi** [comment]
One small remark. I wasn't able to execute the Melos analyze / formatting tasks without problems, as the Melos config file currently uses the `pub` command. I only have a pretty new Dart / Flutter installation so my installation only supports `flutter pub` or `dart pub`. Would it be a good idea to migrate as described [here](https://dart.dev/tools/pub/cmd) or would this break other installations?

**Review by jpnurmi — DISMISSED** [review]
Thanks! LGTM :+1:

**Comment by jpnurmi** [comment]
> Would it be a good idea to migrate as described here or would this break other installations?

Sounds good!

**Comment by jpnurmi** [comment]
P.S. If you want to bump the pubspec version and add an entry to changelog, we can publish this right away.

**Comment by Boehrsi** [comment]
Thanks for the super fast feedback :). I will bump the version and add the changelog entry in the next minutes 👍

**Comment by Boehrsi** [comment]
Added the version increment + change log entry as a separate commit. Hopefully this is fine, as I wasn't sure if I should force push over the old commit instead or if a new commit would be more fitting.

**Review by jpnurmi — APPROVED** [review]
This is perfect. Thank you for the contribution!

**Comment by jpnurmi** [comment]
Published: https://pub.dev/packages/package_info_plus/versions/0.6.4

**Pull request merged**
