### PR TITLE
[device_info] - Web not supported

### PR DESCRIPTION
**Pull request by bruno-garcia**
## Description

The main repo `README` for device_info doesn't match the package `README`:

https://github.com/fluttercommunity/plus_plugins/tree/main/packages/network_info_plus#platform-support

### CODE REVIEW

**Comment by jpnurmi** [comment]
Did device info and network info get mixed up? Network info does not have web support, but device info is available on all platforms.

**Comment by jpnurmi** [comment]
device info for web:

Screenshot from 2021-02-23 23-12-04

**Comment by bruno-garcia** [comment]
Oh that looks good.

**Comment by bruno-garcia** [comment]
I'll update the right readme file

**Pull request closed without merging**
