### PR TITLE
Update (android_alarm_manager_plus): Bump targetSDK to 30, update Android related dependencies

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

Found out that plus plugins use quite a lot of outdated Android dependencies or some config properties, which are deprecated already. As an Android dev decided to go update both plugin and example app Android parts to latest versions of dependencies. 

Both plugin and example won't use Jetifier anymore, which should improve build times.

Additionally, bumped target and compile SDKs to 30 (Android 11). Didn't bump to 31 (Android 12) because it has a behavior change requiring additional permission from the user. I believe such change should be in a separate PR.

My plan is to go over other Android projects in Plus plugins and update their dependencies as well to have them up to date.

## Related Issues

Didn't find anything related to possible issues caused by outdated dependencies here.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by vbuberen** [comment]
I am not sure about the strategy for handling CHANGELOG file. Should contributors add each change as a new version with one new version bump?

**Review by nohli — APPROVED** [review]

**Comment by nohli** [comment]
> I am not sure about the strategy for handling CHANGELOG file. Should contributors add each change as a new version with one new version bump?

I have the same question, since the Contributor Guide (https://github.com/google/charts/issues/678#issuecomment-917855303) says both:

> Before opening a Pull-Request, please increase the build number in the pubspec.yaml and create a new entry in the CHANGELOG.md describing the change. This will help us speed-up the release process for the provided fix or feature.

> Changelogs and version updates are automatically updated by a project maintainer (via Melos). The new version is automatically generated via the commit types and changelogs via the commit messages.

**Comment by miquelbeltran** [comment]
> > Changelogs and version updates are automatically updated by a project maintainer (via Melos). The new version is automatically generated via the commit types and changelogs via the commit messages.

Yes, this is not correct. PRs should contain the changes in the CHANGELOG and bump the version in the pubspec.yaml.

I will modify the document.

**Comment by miquelbeltran** [comment]
@vbuberen the package has been upgraded to v2.0.0. Please merge `main` back into your branch and update the pubspec version accordingly. Thanks!

**Review by miquelbeltran — APPROVED** [review]
LGTM. Needs the right version in the pubspec and the CHANGELOG

**Comment by vbuberen** [comment]
Since 2.0.0 isn't released yet I added mention of my changes to 2.0.0 as well and merged latest `main` changes.

**Comment by miquelbeltran** [comment]
> Since 2.0.0 isn't released yet I added mention of my changes to 2.0.0 as well and merged latest `main` changes.

It IS released! https://pub.dev/packages/android_alarm_manager_plus/versions/2.0.0

**Comment by vbuberen** [comment]
Added

**Comment by miquelbeltran** [comment]
merged and released, thanks!

**Pull request merged**
